// Complete list of countries with ISO codes and phone codes
export interface Country {
  code: string;      // ISO 3166-1 alpha-2
  name: string;
  phoneCode: string;
  phoneFormat?: string;  // Regex pattern for validation
}

export const countries: Country[] = [
  { code: 'US', name: 'United States', phoneCode: '+1', phoneFormat: '^\\+?1?[2-9]\\d{2}[2-9]\\d{6}$' },
  { code: 'CA', name: 'Canada', phoneCode: '+1', phoneFormat: '^\\+?1?[2-9]\\d{2}[2-9]\\d{6}$' },
  { code: 'GB', name: 'United Kingdom', phoneCode: '+44', phoneFormat: '^\\+?44?[1-9]\\d{9,10}$' },
  { code: 'AU', name: 'Australia', phoneCode: '+61', phoneFormat: '^\\+?61?[2-478]\\d{8}$' },
  { code: 'DE', name: 'Germany', phoneCode: '+49', phoneFormat: '^\\+?49?[1-9]\\d{6,14}$' },
  { code: 'FR', name: 'France', phoneCode: '+33', phoneFormat: '^\\+?33?[1-9]\\d{8}$' },
  { code: 'IT', name: 'Italy', phoneCode: '+39', phoneFormat: '^\\+?39?[0-9]\\d{6,11}$' },
  { code: 'ES', name: 'Spain', phoneCode: '+34', phoneFormat: '^\\+?34?[6-9]\\d{8}$' },
  { code: 'NL', name: 'Netherlands', phoneCode: '+31', phoneFormat: '^\\+?31?[1-9]\\d{8}$' },
  { code: 'BE', name: 'Belgium', phoneCode: '+32', phoneFormat: '^\\+?32?[1-9]\\d{7,8}$' },
  { code: 'CH', name: 'Switzerland', phoneCode: '+41', phoneFormat: '^\\+?41?[1-9]\\d{8}$' },
  { code: 'AT', name: 'Austria', phoneCode: '+43', phoneFormat: '^\\+?43?[1-9]\\d{6,13}$' },
  { code: 'SE', name: 'Sweden', phoneCode: '+46', phoneFormat: '^\\+?46?[1-9]\\d{6,12}$' },
  { code: 'NO', name: 'Norway', phoneCode: '+47', phoneFormat: '^\\+?47?[2-9]\\d{7}$' },
  { code: 'DK', name: 'Denmark', phoneCode: '+45', phoneFormat: '^\\+?45?[2-9]\\d{7}$' },
  { code: 'FI', name: 'Finland', phoneCode: '+358', phoneFormat: '^\\+?358?[1-9]\\d{6,10}$' },
  { code: 'IE', name: 'Ireland', phoneCode: '+353', phoneFormat: '^\\+?353?[1-9]\\d{7,9}$' },
  { code: 'PT', name: 'Portugal', phoneCode: '+351', phoneFormat: '^\\+?351?[1-9]\\d{8}$' },
  { code: 'PL', name: 'Poland', phoneCode: '+48', phoneFormat: '^\\+?48?[1-9]\\d{8}$' },
  { code: 'CZ', name: 'Czech Republic', phoneCode: '+420', phoneFormat: '^\\+?420?[1-9]\\d{8}$' },
  { code: 'GR', name: 'Greece', phoneCode: '+30', phoneFormat: '^\\+?30?[2-9]\\d{9}$' },
  { code: 'HU', name: 'Hungary', phoneCode: '+36', phoneFormat: '^\\+?36?[1-9]\\d{8}$' },
  { code: 'RO', name: 'Romania', phoneCode: '+40', phoneFormat: '^\\+?40?[1-9]\\d{8}$' },
  { code: 'BG', name: 'Bulgaria', phoneCode: '+359', phoneFormat: '^\\+?359?[1-9]\\d{7,8}$' },
  { code: 'HR', name: 'Croatia', phoneCode: '+385', phoneFormat: '^\\+?385?[1-9]\\d{7,8}$' },
  { code: 'SK', name: 'Slovakia', phoneCode: '+421', phoneFormat: '^\\+?421?[1-9]\\d{8}$' },
  { code: 'SI', name: 'Slovenia', phoneCode: '+386', phoneFormat: '^\\+?386?[1-9]\\d{7}$' },
  { code: 'LT', name: 'Lithuania', phoneCode: '+370', phoneFormat: '^\\+?370?[1-9]\\d{7}$' },
  { code: 'LV', name: 'Latvia', phoneCode: '+371', phoneFormat: '^\\+?371?[2-9]\\d{7}$' },
  { code: 'EE', name: 'Estonia', phoneCode: '+372', phoneFormat: '^\\+?372?[3-9]\\d{6,7}$' },
  { code: 'CY', name: 'Cyprus', phoneCode: '+357', phoneFormat: '^\\+?357?[2-9]\\d{7}$' },
  { code: 'MT', name: 'Malta', phoneCode: '+356', phoneFormat: '^\\+?356?[2-9]\\d{7}$' },
  { code: 'LU', name: 'Luxembourg', phoneCode: '+352', phoneFormat: '^\\+?352?[2-9]\\d{5,10}$' },
  { code: 'IS', name: 'Iceland', phoneCode: '+354', phoneFormat: '^\\+?354?[3-9]\\d{6}$' },
  { code: 'RU', name: 'Russia', phoneCode: '+7', phoneFormat: '^\\+?7?[3-9]\\d{9}$' },
  { code: 'UA', name: 'Ukraine', phoneCode: '+380', phoneFormat: '^\\+?380?[3-9]\\d{8}$' },
  { code: 'BY', name: 'Belarus', phoneCode: '+375', phoneFormat: '^\\+?375?[1-9]\\d{8}$' },
  { code: 'JP', name: 'Japan', phoneCode: '+81', phoneFormat: '^\\+?81?[1-9]\\d{8,9}$' },
  { code: 'CN', name: 'China', phoneCode: '+86', phoneFormat: '^\\+?86?1[3-9]\\d{9}$' },
  { code: 'KR', name: 'South Korea', phoneCode: '+82', phoneFormat: '^\\+?82?[1-9]\\d{7,9}$' },
  { code: 'IN', name: 'India', phoneCode: '+91', phoneFormat: '^\\+?91?[6-9]\\d{9}$' },
  { code: 'SG', name: 'Singapore', phoneCode: '+65', phoneFormat: '^\\+?65?[3689]\\d{7}$' },
  { code: 'HK', name: 'Hong Kong', phoneCode: '+852', phoneFormat: '^\\+?852?[2-9]\\d{7}$' },
  { code: 'TW', name: 'Taiwan', phoneCode: '+886', phoneFormat: '^\\+?886?[2-9]\\d{7,8}$' },
  { code: 'TH', name: 'Thailand', phoneCode: '+66', phoneFormat: '^\\+?66?[2-9]\\d{7,8}$' },
  { code: 'VN', name: 'Vietnam', phoneCode: '+84', phoneFormat: '^\\+?84?[1-9]\\d{8,9}$' },
  { code: 'PH', name: 'Philippines', phoneCode: '+63', phoneFormat: '^\\+?63?[2-9]\\d{8,9}$' },
  { code: 'MY', name: 'Malaysia', phoneCode: '+60', phoneFormat: '^\\+?60?[1-9]\\d{7,9}$' },
  { code: 'ID', name: 'Indonesia', phoneCode: '+62', phoneFormat: '^\\+?62?[1-9]\\d{8,11}$' },
  { code: 'PK', name: 'Pakistan', phoneCode: '+92', phoneFormat: '^\\+?92?[1-9]\\d{9}$' },
  { code: 'BD', name: 'Bangladesh', phoneCode: '+880', phoneFormat: '^\\+?880?1[3-9]\\d{8}$' },
  { code: 'NP', name: 'Nepal', phoneCode: '+977', phoneFormat: '^\\+?977?[1-9]\\d{8,9}$' },
  { code: 'LK', name: 'Sri Lanka', phoneCode: '+94', phoneFormat: '^\\+?94?[1-9]\\d{8}$' },
  { code: 'AE', name: 'United Arab Emirates', phoneCode: '+971', phoneFormat: '^\\+?971?[2-9]\\d{7,8}$' },
  { code: 'SA', name: 'Saudi Arabia', phoneCode: '+966', phoneFormat: '^\\+?966?[1-9]\\d{8}$' },
  { code: 'QA', name: 'Qatar', phoneCode: '+974', phoneFormat: '^\\+?974?[3-7]\\d{7}$' },
  { code: 'KW', name: 'Kuwait', phoneCode: '+965', phoneFormat: '^\\+?965?[1-9]\\d{7}$' },
  { code: 'BH', name: 'Bahrain', phoneCode: '+973', phoneFormat: '^\\+?973?[1-9]\\d{7}$' },
  { code: 'OM', name: 'Oman', phoneCode: '+968', phoneFormat: '^\\+?968?[2-9]\\d{7}$' },
  { code: 'IL', name: 'Israel', phoneCode: '+972', phoneFormat: '^\\+?972?[2-9]\\d{7,8}$' },
  { code: 'TR', name: 'Turkey', phoneCode: '+90', phoneFormat: '^\\+?90?[2-5]\\d{9}$' },
  { code: 'EG', name: 'Egypt', phoneCode: '+20', phoneFormat: '^\\+?20?1[0-2]\\d{8}$' },
  { code: 'ZA', name: 'South Africa', phoneCode: '+27', phoneFormat: '^\\+?27?[1-9]\\d{8}$' },
  { code: 'NG', name: 'Nigeria', phoneCode: '+234', phoneFormat: '^\\+?234?[1-9]\\d{9}$' },
  { code: 'KE', name: 'Kenya', phoneCode: '+254', phoneFormat: '^\\+?254?[1-9]\\d{8}$' },
  { code: 'GH', name: 'Ghana', phoneCode: '+233', phoneFormat: '^\\+?233?[1-9]\\d{8}$' },
  { code: 'MA', name: 'Morocco', phoneCode: '+212', phoneFormat: '^\\+?212?[5-7]\\d{8}$' },
  { code: 'TN', name: 'Tunisia', phoneCode: '+216', phoneFormat: '^\\+?216?[2-9]\\d{7}$' },
  { code: 'DZ', name: 'Algeria', phoneCode: '+213', phoneFormat: '^\\+?213?[5-7]\\d{8}$' },
  { code: 'MX', name: 'Mexico', phoneCode: '+52', phoneFormat: '^\\+?52?[1-9]\\d{9}$' },
  { code: 'BR', name: 'Brazil', phoneCode: '+55', phoneFormat: '^\\+?55?[1-9]\\d{10}$' },
  { code: 'AR', name: 'Argentina', phoneCode: '+54', phoneFormat: '^\\+?54?[1-9]\\d{9,10}$' },
  { code: 'CL', name: 'Chile', phoneCode: '+56', phoneFormat: '^\\+?56?[2-9]\\d{8}$' },
  { code: 'CO', name: 'Colombia', phoneCode: '+57', phoneFormat: '^\\+?57?[1-9]\\d{9}$' },
  { code: 'PE', name: 'Peru', phoneCode: '+51', phoneFormat: '^\\+?51?[1-9]\\d{8}$' },
  { code: 'VE', name: 'Venezuela', phoneCode: '+58', phoneFormat: '^\\+?58?[1-9]\\d{9}$' },
  { code: 'EC', name: 'Ecuador', phoneCode: '+593', phoneFormat: '^\\+?593?[2-9]\\d{7,8}$' },
  { code: 'UY', name: 'Uruguay', phoneCode: '+598', phoneFormat: '^\\+?598?[2-9]\\d{7}$' },
  { code: 'PY', name: 'Paraguay', phoneCode: '+595', phoneFormat: '^\\+?595?[1-9]\\d{8}$' },
  { code: 'BO', name: 'Bolivia', phoneCode: '+591', phoneFormat: '^\\+?591?[2-9]\\d{7}$' },
  { code: 'CR', name: 'Costa Rica', phoneCode: '+506', phoneFormat: '^\\+?506?[2-8]\\d{7}$' },
  { code: 'PA', name: 'Panama', phoneCode: '+507', phoneFormat: '^\\+?507?[2-9]\\d{6,7}$' },
  { code: 'GT', name: 'Guatemala', phoneCode: '+502', phoneFormat: '^\\+?502?[2-9]\\d{7}$' },
  { code: 'HN', name: 'Honduras', phoneCode: '+504', phoneFormat: '^\\+?504?[2-9]\\d{7}$' },
  { code: 'SV', name: 'El Salvador', phoneCode: '+503', phoneFormat: '^\\+?503?[2-9]\\d{7}$' },
  { code: 'NI', name: 'Nicaragua', phoneCode: '+505', phoneFormat: '^\\+?505?[2-9]\\d{7}$' },
  { code: 'DO', name: 'Dominican Republic', phoneCode: '+1', phoneFormat: '^\\+?1?809\\d{7}$' },
  { code: 'PR', name: 'Puerto Rico', phoneCode: '+1', phoneFormat: '^\\+?1?787\\d{7}$' },
  { code: 'JM', name: 'Jamaica', phoneCode: '+1', phoneFormat: '^\\+?1?876\\d{7}$' },
  { code: 'TT', name: 'Trinidad and Tobago', phoneCode: '+1', phoneFormat: '^\\+?1?868\\d{7}$' },
  { code: 'BB', name: 'Barbados', phoneCode: '+1', phoneFormat: '^\\+?1?246\\d{7}$' },
  { code: 'BS', name: 'Bahamas', phoneCode: '+1', phoneFormat: '^\\+?1?242\\d{7}$' },
  { code: 'CU', name: 'Cuba', phoneCode: '+53', phoneFormat: '^\\+?53?[1-9]\\d{7}$' },
  { code: 'NZ', name: 'New Zealand', phoneCode: '+64', phoneFormat: '^\\+?64?[2-9]\\d{7,9}$' },
  { code: 'FJ', name: 'Fiji', phoneCode: '+679', phoneFormat: '^\\+?679?[1-9]\\d{6}$' },
  { code: 'AF', name: 'Afghanistan', phoneCode: '+93', phoneFormat: '^\\+?93?[1-9]\\d{8}$' },
  { code: 'AL', name: 'Albania', phoneCode: '+355', phoneFormat: '^\\+?355?[1-9]\\d{7,8}$' },
  { code: 'AD', name: 'Andorra', phoneCode: '+376', phoneFormat: '^\\+?376?[1-9]\\d{5}$' },
  { code: 'AO', name: 'Angola', phoneCode: '+244', phoneFormat: '^\\+?244?[1-9]\\d{8}$' },
  { code: 'AM', name: 'Armenia', phoneCode: '+374', phoneFormat: '^\\+?374?[1-9]\\d{7}$' },
  { code: 'AZ', name: 'Azerbaijan', phoneCode: '+994', phoneFormat: '^\\+?994?[1-9]\\d{8}$' },
  { code: 'BA', name: 'Bosnia and Herzegovina', phoneCode: '+387', phoneFormat: '^\\+?387?[1-9]\\d{7}$' },
  { code: 'BW', name: 'Botswana', phoneCode: '+267', phoneFormat: '^\\+?267?[1-9]\\d{6,7}$' },
  { code: 'BN', name: 'Brunei', phoneCode: '+673', phoneFormat: '^\\+?673?[2-9]\\d{6}$' },
  { code: 'KH', name: 'Cambodia', phoneCode: '+855', phoneFormat: '^\\+?855?[1-9]\\d{7,8}$' },
  { code: 'CM', name: 'Cameroon', phoneCode: '+237', phoneFormat: '^\\+?237?[2-9]\\d{7,8}$' },
  { code: 'CV', name: 'Cape Verde', phoneCode: '+238', phoneFormat: '^\\+?238?[2-9]\\d{6}$' },
  { code: 'CF', name: 'Central African Republic', phoneCode: '+236', phoneFormat: '^\\+?236?[2-9]\\d{7}$' },
  { code: 'TD', name: 'Chad', phoneCode: '+235', phoneFormat: '^\\+?235?[2-9]\\d{7}$' },
  { code: 'CD', name: 'Congo (DRC)', phoneCode: '+243', phoneFormat: '^\\+?243?[1-9]\\d{8}$' },
  { code: 'CG', name: 'Congo (Republic)', phoneCode: '+242', phoneFormat: '^\\+?242?[0-9]\\d{8}$' },
  { code: 'CI', name: 'Ivory Coast', phoneCode: '+225', phoneFormat: '^\\+?225?[0-9]\\d{9}$' },
  { code: 'DJ', name: 'Djibouti', phoneCode: '+253', phoneFormat: '^\\+?253?[1-9]\\d{7}$' },
  { code: 'GQ', name: 'Equatorial Guinea', phoneCode: '+240', phoneFormat: '^\\+?240?[2-9]\\d{8}$' },
  { code: 'ER', name: 'Eritrea', phoneCode: '+291', phoneFormat: '^\\+?291?[1-9]\\d{6}$' },
  { code: 'SZ', name: 'Eswatini', phoneCode: '+268', phoneFormat: '^\\+?268?[2-9]\\d{7}$' },
  { code: 'ET', name: 'Ethiopia', phoneCode: '+251', phoneFormat: '^\\+?251?[1-9]\\d{8}$' },
  { code: 'GA', name: 'Gabon', phoneCode: '+241', phoneFormat: '^\\+?241?[0-9]\\d{7}$' },
  { code: 'GM', name: 'Gambia', phoneCode: '+220', phoneFormat: '^\\+?220?[2-9]\\d{6}$' },
  { code: 'GE', name: 'Georgia', phoneCode: '+995', phoneFormat: '^\\+?995?[1-9]\\d{8}$' },
  { code: 'GN', name: 'Guinea', phoneCode: '+224', phoneFormat: '^\\+?224?[1-9]\\d{8}$' },
  { code: 'GW', name: 'Guinea-Bissau', phoneCode: '+245', phoneFormat: '^\\+?245?[5-9]\\d{6}$' },
  { code: 'GY', name: 'Guyana', phoneCode: '+592', phoneFormat: '^\\+?592?[2-9]\\d{6}$' },
  { code: 'HT', name: 'Haiti', phoneCode: '+509', phoneFormat: '^\\+?509?[2-9]\\d{7}$' },
  { code: 'IQ', name: 'Iraq', phoneCode: '+964', phoneFormat: '^\\+?964?[1-9]\\d{8,9}$' },
  { code: 'IR', name: 'Iran', phoneCode: '+98', phoneFormat: '^\\+?98?[1-9]\\d{9}$' },
  { code: 'JO', name: 'Jordan', phoneCode: '+962', phoneFormat: '^\\+?962?[1-9]\\d{7,8}$' },
  { code: 'KZ', name: 'Kazakhstan', phoneCode: '+7', phoneFormat: '^\\+?7?[67]\\d{9}$' },
  { code: 'KG', name: 'Kyrgyzstan', phoneCode: '+996', phoneFormat: '^\\+?996?[1-9]\\d{8}$' },
  { code: 'LA', name: 'Laos', phoneCode: '+856', phoneFormat: '^\\+?856?[1-9]\\d{7,9}$' },
  { code: 'LB', name: 'Lebanon', phoneCode: '+961', phoneFormat: '^\\+?961?[1-9]\\d{6,7}$' },
  { code: 'LS', name: 'Lesotho', phoneCode: '+266', phoneFormat: '^\\+?266?[2-9]\\d{7}$' },
  { code: 'LR', name: 'Liberia', phoneCode: '+231', phoneFormat: '^\\+?231?[2-9]\\d{7}$' },
  { code: 'LY', name: 'Libya', phoneCode: '+218', phoneFormat: '^\\+?218?[1-9]\\d{8}$' },
  { code: 'LI', name: 'Liechtenstein', phoneCode: '+423', phoneFormat: '^\\+?423?[1-9]\\d{6}$' },
  { code: 'MK', name: 'North Macedonia', phoneCode: '+389', phoneFormat: '^\\+?389?[2-9]\\d{7}$' },
  { code: 'MG', name: 'Madagascar', phoneCode: '+261', phoneFormat: '^\\+?261?[2-9]\\d{8}$' },
  { code: 'MW', name: 'Malawi', phoneCode: '+265', phoneFormat: '^\\+?265?[1-9]\\d{8}$' },
  { code: 'MV', name: 'Maldives', phoneCode: '+960', phoneFormat: '^\\+?960?[3-9]\\d{6}$' },
  { code: 'ML', name: 'Mali', phoneCode: '+223', phoneFormat: '^\\+?223?[2-9]\\d{7}$' },
  { code: 'MR', name: 'Mauritania', phoneCode: '+222', phoneFormat: '^\\+?222?[2-9]\\d{7}$' },
  { code: 'MU', name: 'Mauritius', phoneCode: '+230', phoneFormat: '^\\+?230?[2-9]\\d{6,7}$' },
  { code: 'MD', name: 'Moldova', phoneCode: '+373', phoneFormat: '^\\+?373?[1-9]\\d{7}$' },
  { code: 'MC', name: 'Monaco', phoneCode: '+377', phoneFormat: '^\\+?377?[1-9]\\d{7}$' },
  { code: 'MN', name: 'Mongolia', phoneCode: '+976', phoneFormat: '^\\+?976?[1-9]\\d{7}$' },
  { code: 'ME', name: 'Montenegro', phoneCode: '+382', phoneFormat: '^\\+?382?[1-9]\\d{7}$' },
  { code: 'MZ', name: 'Mozambique', phoneCode: '+258', phoneFormat: '^\\+?258?[1-9]\\d{8}$' },
  { code: 'MM', name: 'Myanmar', phoneCode: '+95', phoneFormat: '^\\+?95?[1-9]\\d{7,9}$' },
  { code: 'NA', name: 'Namibia', phoneCode: '+264', phoneFormat: '^\\+?264?[1-9]\\d{8}$' },
  { code: 'NE', name: 'Niger', phoneCode: '+227', phoneFormat: '^\\+?227?[2-9]\\d{7}$' },
  { code: 'KP', name: 'North Korea', phoneCode: '+850', phoneFormat: '^\\+?850?[1-9]\\d{9}$' },
  { code: 'PS', name: 'Palestine', phoneCode: '+970', phoneFormat: '^\\+?970?[1-9]\\d{8}$' },
  { code: 'RW', name: 'Rwanda', phoneCode: '+250', phoneFormat: '^\\+?250?[1-9]\\d{8}$' },
  { code: 'SM', name: 'San Marino', phoneCode: '+378', phoneFormat: '^\\+?378?[0-9]\\d{9}$' },
  { code: 'SN', name: 'Senegal', phoneCode: '+221', phoneFormat: '^\\+?221?[1-9]\\d{8}$' },
  { code: 'RS', name: 'Serbia', phoneCode: '+381', phoneFormat: '^\\+?381?[1-9]\\d{7,8}$' },
  { code: 'SC', name: 'Seychelles', phoneCode: '+248', phoneFormat: '^\\+?248?[2-9]\\d{6}$' },
  { code: 'SL', name: 'Sierra Leone', phoneCode: '+232', phoneFormat: '^\\+?232?[2-9]\\d{7}$' },
  { code: 'SO', name: 'Somalia', phoneCode: '+252', phoneFormat: '^\\+?252?[1-9]\\d{7,8}$' },
  { code: 'SS', name: 'South Sudan', phoneCode: '+211', phoneFormat: '^\\+?211?[1-9]\\d{8}$' },
  { code: 'SD', name: 'Sudan', phoneCode: '+249', phoneFormat: '^\\+?249?[1-9]\\d{8}$' },
  { code: 'SR', name: 'Suriname', phoneCode: '+597', phoneFormat: '^\\+?597?[1-9]\\d{5,6}$' },
  { code: 'SY', name: 'Syria', phoneCode: '+963', phoneFormat: '^\\+?963?[1-9]\\d{8}$' },
  { code: 'TJ', name: 'Tajikistan', phoneCode: '+992', phoneFormat: '^\\+?992?[1-9]\\d{8}$' },
  { code: 'TZ', name: 'Tanzania', phoneCode: '+255', phoneFormat: '^\\+?255?[1-9]\\d{8}$' },
  { code: 'TL', name: 'Timor-Leste', phoneCode: '+670', phoneFormat: '^\\+?670?[1-9]\\d{6}$' },
  { code: 'TG', name: 'Togo', phoneCode: '+228', phoneFormat: '^\\+?228?[2-9]\\d{7}$' },
  { code: 'TM', name: 'Turkmenistan', phoneCode: '+993', phoneFormat: '^\\+?993?[1-9]\\d{7}$' },
  { code: 'UG', name: 'Uganda', phoneCode: '+256', phoneFormat: '^\\+?256?[1-9]\\d{8}$' },
  { code: 'UZ', name: 'Uzbekistan', phoneCode: '+998', phoneFormat: '^\\+?998?[1-9]\\d{8}$' },
  { code: 'VA', name: 'Vatican City', phoneCode: '+39', phoneFormat: '^\\+?39?06698\\d{5}$' },
  { code: 'YE', name: 'Yemen', phoneCode: '+967', phoneFormat: '^\\+?967?[1-9]\\d{8}$' },
  { code: 'ZM', name: 'Zambia', phoneCode: '+260', phoneFormat: '^\\+?260?[1-9]\\d{8}$' },
  { code: 'ZW', name: 'Zimbabwe', phoneCode: '+263', phoneFormat: '^\\+?263?[1-9]\\d{8}$' },
];

// Get country by code
export function getCountryByCode(code: string): Country | undefined {
  return countries.find(c => c.code === code);
}

// Get country by name
export function getCountryByName(name: string): Country | undefined {
  return countries.find(c => c.name.toLowerCase() === name.toLowerCase());
}

// Sorted countries (US and Canada first, then alphabetical)
export function getSortedCountries(): Country[] {
  const priority = ['US', 'CA', 'GB', 'AU'];
  const priorityCountries = priority
    .map(code => countries.find(c => c.code === code))
    .filter((c): c is Country => c !== undefined);

  const otherCountries = countries
    .filter(c => !priority.includes(c.code))
    .sort((a, b) => a.name.localeCompare(b.name));

  return [...priorityCountries, ...otherCountries];
}
