// Pre-filled templates for common products and services a startup might offer
export interface OfferedProductTemplate {
  name: string;
  description: string;
  category: string;
  icon: string;
  pricing_model: string;
  price_example: string;
}

export const offeredProductTemplates: OfferedProductTemplate[] = [
  // ============ SaaS Products ============
  {
    name: 'SaaS Platform',
    description: 'Cloud-based software application with subscription access.',
    category: 'saas',
    icon: '☁️',
    pricing_model: 'subscription',
    price_example: '$29-299/mo',
  },
  {
    name: 'API Service',
    description: 'RESTful or GraphQL API for developers to integrate with.',
    category: 'saas',
    icon: '🔌',
    pricing_model: 'usage',
    price_example: '$0.001/request',
  },
  {
    name: 'Data Analytics Platform',
    description: 'Business intelligence and data visualization dashboard.',
    category: 'saas',
    icon: '📊',
    pricing_model: 'subscription',
    price_example: '$99-499/mo',
  },
  {
    name: 'Project Management Tool',
    description: 'Team collaboration and project tracking software.',
    category: 'saas',
    icon: '📋',
    pricing_model: 'subscription',
    price_example: '$10-25/user/mo',
  },
  {
    name: 'CRM Platform',
    description: 'Customer relationship management and sales pipeline software.',
    category: 'saas',
    icon: '👥',
    pricing_model: 'subscription',
    price_example: '$25-150/user/mo',
  },
  {
    name: 'Email Marketing Platform',
    description: 'Email campaign management and automation tool.',
    category: 'saas',
    icon: '📧',
    pricing_model: 'subscription',
    price_example: '$15-299/mo',
  },
  {
    name: 'Helpdesk Software',
    description: 'Customer support ticketing and knowledge base system.',
    category: 'saas',
    icon: '🎫',
    pricing_model: 'subscription',
    price_example: '$15-50/agent/mo',
  },
  {
    name: 'E-commerce Platform',
    description: 'Online store builder with payment processing.',
    category: 'saas',
    icon: '🛒',
    pricing_model: 'subscription',
    price_example: '$29-299/mo',
  },
  {
    name: 'Scheduling Software',
    description: 'Appointment booking and calendar management tool.',
    category: 'saas',
    icon: '📅',
    pricing_model: 'freemium',
    price_example: '$0-15/user/mo',
  },
  {
    name: 'HR Management System',
    description: 'Employee management, payroll, and benefits administration.',
    category: 'saas',
    icon: '👔',
    pricing_model: 'subscription',
    price_example: '$8-15/employee/mo',
  },
  {
    name: 'Accounting Software',
    description: 'Bookkeeping, invoicing, and financial reporting tool.',
    category: 'saas',
    icon: '📗',
    pricing_model: 'subscription',
    price_example: '$15-70/mo',
  },
  {
    name: 'Document Management',
    description: 'File storage, sharing, and collaboration platform.',
    category: 'saas',
    icon: '📁',
    pricing_model: 'subscription',
    price_example: '$10-25/user/mo',
  },
  {
    name: 'Learning Management System',
    description: 'Online course creation and training platform.',
    category: 'saas',
    icon: '🎓',
    pricing_model: 'subscription',
    price_example: '$99-999/mo',
  },
  {
    name: 'Video Conferencing',
    description: 'Video meetings and webinar hosting platform.',
    category: 'saas',
    icon: '📹',
    pricing_model: 'freemium',
    price_example: '$0-25/host/mo',
  },
  {
    name: 'Survey & Forms Tool',
    description: 'Online surveys, forms, and feedback collection.',
    category: 'saas',
    icon: '📝',
    pricing_model: 'freemium',
    price_example: '$0-99/mo',
  },

  // ============ Software Products ============
  {
    name: 'Desktop Application',
    description: 'Native software for Windows, Mac, or Linux.',
    category: 'software',
    icon: '💻',
    pricing_model: 'one-time',
    price_example: '$49-499',
  },
  {
    name: 'Mobile App',
    description: 'iOS and/or Android mobile application.',
    category: 'software',
    icon: '📱',
    pricing_model: 'freemium',
    price_example: 'Free + IAP',
  },
  {
    name: 'Browser Extension',
    description: 'Chrome, Firefox, or Safari browser add-on.',
    category: 'software',
    icon: '🧩',
    pricing_model: 'freemium',
    price_example: '$0-9.99/mo',
  },
  {
    name: 'WordPress Plugin',
    description: 'Plugin extending WordPress functionality.',
    category: 'software',
    icon: '🔧',
    pricing_model: 'one-time',
    price_example: '$29-199/yr',
  },
  {
    name: 'Shopify App',
    description: 'E-commerce app for Shopify stores.',
    category: 'software',
    icon: '🛍️',
    pricing_model: 'subscription',
    price_example: '$9-99/mo',
  },
  {
    name: 'SDK / Library',
    description: 'Software development kit for developers.',
    category: 'software',
    icon: '📦',
    pricing_model: 'freemium',
    price_example: 'Open source + Enterprise',
  },
  {
    name: 'Game',
    description: 'Video game for PC, console, or mobile.',
    category: 'software',
    icon: '🎮',
    pricing_model: 'one-time',
    price_example: '$4.99-59.99',
  },
  {
    name: 'AI/ML Model',
    description: 'Pre-trained machine learning model or AI service.',
    category: 'software',
    icon: '🤖',
    pricing_model: 'usage',
    price_example: '$0.01-0.10/inference',
  },

  // ============ Consulting Services ============
  {
    name: 'Strategy Consulting',
    description: 'Business strategy and planning advisory services.',
    category: 'consulting',
    icon: '🎯',
    pricing_model: 'project',
    price_example: '$5K-50K/project',
  },
  {
    name: 'Technical Consulting',
    description: 'Software architecture and technology advisory.',
    category: 'consulting',
    icon: '⚙️',
    pricing_model: 'hourly',
    price_example: '$150-400/hr',
  },
  {
    name: 'Marketing Consulting',
    description: 'Marketing strategy, branding, and growth advisory.',
    category: 'consulting',
    icon: '📢',
    pricing_model: 'project',
    price_example: '$3K-25K/project',
  },
  {
    name: 'Financial Consulting',
    description: 'Financial planning, fundraising, and accounting advisory.',
    category: 'consulting',
    icon: '💰',
    pricing_model: 'hourly',
    price_example: '$200-500/hr',
  },
  {
    name: 'Legal Consulting',
    description: 'Legal advisory for contracts, compliance, and IP.',
    category: 'consulting',
    icon: '⚖️',
    pricing_model: 'hourly',
    price_example: '$250-600/hr',
  },
  {
    name: 'HR Consulting',
    description: 'Human resources, hiring, and organizational advisory.',
    category: 'consulting',
    icon: '👥',
    pricing_model: 'project',
    price_example: '$2K-15K/project',
  },
  {
    name: 'Security Consulting',
    description: 'Cybersecurity assessment and advisory services.',
    category: 'consulting',
    icon: '🔒',
    pricing_model: 'project',
    price_example: '$5K-50K/project',
  },
  {
    name: 'UX/Design Consulting',
    description: 'User experience and product design advisory.',
    category: 'consulting',
    icon: '🎨',
    pricing_model: 'hourly',
    price_example: '$100-250/hr',
  },

  // ============ Professional Services ============
  {
    name: 'Custom Development',
    description: 'Bespoke software development services.',
    category: 'service',
    icon: '👨‍💻',
    pricing_model: 'project',
    price_example: '$10K-500K',
  },
  {
    name: 'Web Development',
    description: 'Website design and development services.',
    category: 'service',
    icon: '🌐',
    pricing_model: 'project',
    price_example: '$2K-50K',
  },
  {
    name: 'Mobile App Development',
    description: 'iOS and Android app development services.',
    category: 'service',
    icon: '📲',
    pricing_model: 'project',
    price_example: '$25K-200K',
  },
  {
    name: 'DevOps Services',
    description: 'Infrastructure, CI/CD, and cloud operations.',
    category: 'service',
    icon: '🚀',
    pricing_model: 'hourly',
    price_example: '$100-200/hr',
  },
  {
    name: 'QA & Testing',
    description: 'Software testing and quality assurance services.',
    category: 'service',
    icon: '🧪',
    pricing_model: 'hourly',
    price_example: '$50-100/hr',
  },
  {
    name: 'Data Engineering',
    description: 'Data pipeline, ETL, and analytics engineering.',
    category: 'service',
    icon: '🔧',
    pricing_model: 'hourly',
    price_example: '$125-250/hr',
  },
  {
    name: 'UI/UX Design',
    description: 'Interface design and user experience services.',
    category: 'service',
    icon: '🎨',
    pricing_model: 'project',
    price_example: '$3K-30K',
  },
  {
    name: 'Graphic Design',
    description: 'Branding, marketing materials, and visual design.',
    category: 'service',
    icon: '🖼️',
    pricing_model: 'project',
    price_example: '$500-10K',
  },
  {
    name: 'Content Writing',
    description: 'Blog posts, copywriting, and content creation.',
    category: 'service',
    icon: '✍️',
    pricing_model: 'project',
    price_example: '$100-2K/piece',
  },
  {
    name: 'Video Production',
    description: 'Video creation, editing, and production services.',
    category: 'service',
    icon: '🎬',
    pricing_model: 'project',
    price_example: '$1K-25K',
  },
  {
    name: 'SEO Services',
    description: 'Search engine optimization and content strategy.',
    category: 'service',
    icon: '🔍',
    pricing_model: 'subscription',
    price_example: '$500-5K/mo',
  },
  {
    name: 'Social Media Management',
    description: 'Social media content and community management.',
    category: 'service',
    icon: '📱',
    pricing_model: 'subscription',
    price_example: '$500-3K/mo',
  },
  {
    name: 'PPC Advertising',
    description: 'Paid advertising campaign management.',
    category: 'service',
    icon: '🎯',
    pricing_model: 'subscription',
    price_example: '$1K-10K/mo + ad spend',
  },
  {
    name: 'Email Marketing Management',
    description: 'Email campaign creation and management.',
    category: 'service',
    icon: '📧',
    pricing_model: 'subscription',
    price_example: '$500-2K/mo',
  },

  // ============ Subscription Products ============
  {
    name: 'Newsletter',
    description: 'Premium newsletter or content subscription.',
    category: 'subscription',
    icon: '📰',
    pricing_model: 'subscription',
    price_example: '$5-50/mo',
  },
  {
    name: 'Membership Community',
    description: 'Exclusive community access and content.',
    category: 'subscription',
    icon: '🏛️',
    pricing_model: 'subscription',
    price_example: '$29-199/mo',
  },
  {
    name: 'Online Course',
    description: 'Self-paced educational video course.',
    category: 'subscription',
    icon: '🎓',
    pricing_model: 'one-time',
    price_example: '$97-997',
  },
  {
    name: 'Coaching Program',
    description: 'Group or 1:1 coaching subscription.',
    category: 'subscription',
    icon: '🏆',
    pricing_model: 'subscription',
    price_example: '$199-999/mo',
  },
  {
    name: 'Subscription Box',
    description: 'Physical product subscription box service.',
    category: 'subscription',
    icon: '📦',
    pricing_model: 'subscription',
    price_example: '$19-99/mo',
  },
  {
    name: 'Stock Media Library',
    description: 'Access to stock photos, videos, or music.',
    category: 'subscription',
    icon: '🖼️',
    pricing_model: 'subscription',
    price_example: '$19-199/mo',
  },

  // ============ License Products ============
  {
    name: 'Software License',
    description: 'Perpetual or term license for software.',
    category: 'license',
    icon: '📜',
    pricing_model: 'one-time',
    price_example: '$99-999',
  },
  {
    name: 'Enterprise License',
    description: 'Enterprise-wide software licensing.',
    category: 'license',
    icon: '🏢',
    pricing_model: 'subscription',
    price_example: '$10K-100K/yr',
  },
  {
    name: 'White Label License',
    description: 'License to rebrand and resell software.',
    category: 'license',
    icon: '🏷️',
    pricing_model: 'one-time',
    price_example: '$5K-50K',
  },
  {
    name: 'Patent License',
    description: 'License to use patented technology.',
    category: 'license',
    icon: '💡',
    pricing_model: 'custom',
    price_example: 'Royalty-based',
  },
  {
    name: 'Template/Theme',
    description: 'Website template, theme, or design kit.',
    category: 'license',
    icon: '🎨',
    pricing_model: 'one-time',
    price_example: '$29-199',
  },
  {
    name: 'Font License',
    description: 'Typography and font licensing.',
    category: 'license',
    icon: '🔤',
    pricing_model: 'one-time',
    price_example: '$25-500',
  },

  // ============ Hardware Products ============
  {
    name: 'IoT Device',
    description: 'Internet-connected hardware device.',
    category: 'hardware',
    icon: '📡',
    pricing_model: 'one-time',
    price_example: '$99-999',
  },
  {
    name: 'Consumer Electronics',
    description: 'Consumer electronic product.',
    category: 'hardware',
    icon: '🔌',
    pricing_model: 'one-time',
    price_example: '$49-499',
  },
  {
    name: 'Hardware Kit',
    description: 'Developer or maker hardware kit.',
    category: 'hardware',
    icon: '🔧',
    pricing_model: 'one-time',
    price_example: '$29-199',
  },
  {
    name: 'Wearable Device',
    description: 'Wearable technology product.',
    category: 'hardware',
    icon: '⌚',
    pricing_model: 'one-time',
    price_example: '$149-499',
  },
  {
    name: 'Smart Home Device',
    description: 'Home automation hardware product.',
    category: 'hardware',
    icon: '🏠',
    pricing_model: 'one-time',
    price_example: '$29-299',
  },

  // ============ Managed Services ============
  {
    name: 'Managed Hosting',
    description: 'Fully managed server and application hosting.',
    category: 'service',
    icon: '🖥️',
    pricing_model: 'subscription',
    price_example: '$100-1K/mo',
  },
  {
    name: 'Managed Security',
    description: '24/7 security monitoring and incident response.',
    category: 'service',
    icon: '🛡️',
    pricing_model: 'subscription',
    price_example: '$500-5K/mo',
  },
  {
    name: 'IT Support',
    description: 'Help desk and IT support services.',
    category: 'service',
    icon: '🎧',
    pricing_model: 'subscription',
    price_example: '$50-150/user/mo',
  },
  {
    name: 'Bookkeeping Service',
    description: 'Monthly bookkeeping and financial management.',
    category: 'service',
    icon: '📚',
    pricing_model: 'subscription',
    price_example: '$200-1K/mo',
  },
  {
    name: 'Virtual Assistant',
    description: 'Administrative and executive assistance.',
    category: 'service',
    icon: '👩‍💼',
    pricing_model: 'hourly',
    price_example: '$15-50/hr',
  },
  {
    name: 'Fractional CTO/CMO',
    description: 'Part-time executive leadership services.',
    category: 'consulting',
    icon: '👔',
    pricing_model: 'subscription',
    price_example: '$2K-10K/mo',
  },

  // ============ Digital Products ============
  {
    name: 'E-book',
    description: 'Digital book or guide.',
    category: 'other',
    icon: '📖',
    pricing_model: 'one-time',
    price_example: '$9-49',
  },
  {
    name: 'Digital Download',
    description: 'Downloadable digital asset or tool.',
    category: 'other',
    icon: '⬇️',
    pricing_model: 'one-time',
    price_example: '$5-99',
  },
  {
    name: 'Spreadsheet Template',
    description: 'Pre-built Excel or Google Sheets template.',
    category: 'other',
    icon: '📊',
    pricing_model: 'one-time',
    price_example: '$19-99',
  },
  {
    name: 'Notion Template',
    description: 'Pre-built Notion workspace template.',
    category: 'other',
    icon: '📝',
    pricing_model: 'one-time',
    price_example: '$19-79',
  },
  {
    name: 'Printable/PDF',
    description: 'Downloadable printable documents.',
    category: 'other',
    icon: '🖨️',
    pricing_model: 'one-time',
    price_example: '$5-29',
  },
  {
    name: 'Audio Content',
    description: 'Podcast, audiobook, or audio course.',
    category: 'other',
    icon: '🎧',
    pricing_model: 'one-time',
    price_example: '$15-99',
  },
];

// Group templates by category for easier browsing
export const offeredTemplatesByCategory = offeredProductTemplates.reduce((acc, template) => {
  if (!acc[template.category]) {
    acc[template.category] = [];
  }
  acc[template.category].push(template);
  return acc;
}, {} as Record<string, OfferedProductTemplate[]>);

// Search templates
export const searchOfferedTemplates = (query: string): OfferedProductTemplate[] => {
  const lowerQuery = query.toLowerCase();
  return offeredProductTemplates.filter(t =>
    t.name.toLowerCase().includes(lowerQuery) ||
    t.description.toLowerCase().includes(lowerQuery) ||
    t.category.toLowerCase().includes(lowerQuery)
  );
};
