// Pre-filled templates for common services and tools
export interface ServiceTemplate {
  name: string;
  vendor: string;
  category: string;
  icon: string;
  description: string;
  features: string;
  url: string;
  login_url: string;
  is_paid: boolean;
  billing_cycle?: string;
  license_type?: string;
}

export const serviceTemplates: ServiceTemplate[] = [
  // ============ AWS Services ============
  {
    name: 'AWS Lambda',
    vendor: 'Amazon Web Services',
    category: 'infrastructure',
    icon: '⚡',
    description: 'Serverless compute service that runs code in response to events and automatically manages compute resources.',
    features: 'Serverless, Auto-scaling, Pay-per-use, Multiple runtimes, Event-driven, VPC support',
    url: 'https://aws.amazon.com/lambda/',
    login_url: 'https://console.aws.amazon.com/lambda/',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'custom',
  },
  {
    name: 'AWS EC2',
    vendor: 'Amazon Web Services',
    category: 'infrastructure',
    icon: '🖥️',
    description: 'Elastic Compute Cloud - scalable virtual servers in the cloud for running applications.',
    features: 'Virtual servers, Auto-scaling, Multiple instance types, Spot instances, Reserved capacity, EBS storage',
    url: 'https://aws.amazon.com/ec2/',
    login_url: 'https://console.aws.amazon.com/ec2/',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'custom',
  },
  {
    name: 'AWS Lightsail',
    vendor: 'Amazon Web Services',
    category: 'infrastructure',
    icon: '💡',
    description: 'Simple virtual private servers with predictable pricing for small-scale applications and websites.',
    features: 'Fixed pricing, SSD storage, Static IPs, DNS management, Snapshots, Load balancers',
    url: 'https://aws.amazon.com/lightsail/',
    login_url: 'https://lightsail.aws.amazon.com/',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'starter',
  },
  {
    name: 'AWS S3',
    vendor: 'Amazon Web Services',
    category: 'infrastructure',
    icon: '🪣',
    description: 'Simple Storage Service - scalable object storage for data backup, archival, and analytics.',
    features: 'Object storage, Versioning, Lifecycle policies, Cross-region replication, Static hosting, Glacier integration',
    url: 'https://aws.amazon.com/s3/',
    login_url: 'https://console.aws.amazon.com/s3/',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'custom',
  },
  {
    name: 'AWS RDS',
    vendor: 'Amazon Web Services',
    category: 'infrastructure',
    icon: '🗄️',
    description: 'Relational Database Service - managed database service for MySQL, PostgreSQL, MariaDB, Oracle, and SQL Server.',
    features: 'Managed databases, Auto backups, Multi-AZ, Read replicas, Auto scaling, Performance insights',
    url: 'https://aws.amazon.com/rds/',
    login_url: 'https://console.aws.amazon.com/rds/',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'custom',
  },
  {
    name: 'AWS CloudFront',
    vendor: 'Amazon Web Services',
    category: 'infrastructure',
    icon: '🌐',
    description: 'Content delivery network (CDN) for fast, secure delivery of websites, APIs, and streaming content.',
    features: 'Global CDN, Edge locations, SSL/TLS, DDoS protection, Lambda@Edge, Real-time logs',
    url: 'https://aws.amazon.com/cloudfront/',
    login_url: 'https://console.aws.amazon.com/cloudfront/',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'custom',
  },
  {
    name: 'AWS Route 53',
    vendor: 'Amazon Web Services',
    category: 'infrastructure',
    icon: '🗺️',
    description: 'Scalable DNS and domain registration service with health checking and traffic routing.',
    features: 'DNS management, Domain registration, Health checks, Traffic routing, DNSSEC, Private DNS',
    url: 'https://aws.amazon.com/route53/',
    login_url: 'https://console.aws.amazon.com/route53/',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'custom',
  },
  {
    name: 'AWS SES',
    vendor: 'Amazon Web Services',
    category: 'communication',
    icon: '📧',
    description: 'Simple Email Service - scalable email sending and receiving service for transactional and marketing emails.',
    features: 'Transactional email, Bulk sending, Email receiving, Templates, Analytics, Deliverability tools',
    url: 'https://aws.amazon.com/ses/',
    login_url: 'https://console.aws.amazon.com/ses/',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'custom',
  },

  // ============ Azure Services ============
  {
    name: 'Azure Functions',
    vendor: 'Microsoft Azure',
    category: 'infrastructure',
    icon: '⚡',
    description: 'Serverless compute service for running event-driven code without managing infrastructure.',
    features: 'Serverless, Multiple triggers, Durable functions, Premium plan, VNET integration, Bindings',
    url: 'https://azure.microsoft.com/en-us/products/functions/',
    login_url: 'https://portal.azure.com/#blade/HubsExtension/BrowseResource/resourceType/Microsoft.Web%2Fsites/kind/functionapp',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'custom',
  },
  {
    name: 'Azure Virtual Machines',
    vendor: 'Microsoft Azure',
    category: 'infrastructure',
    icon: '🖥️',
    description: 'Scalable on-demand virtualized computing resources in the Azure cloud.',
    features: 'Windows/Linux VMs, Scale sets, Spot VMs, Reserved instances, Hybrid benefit, Managed disks',
    url: 'https://azure.microsoft.com/en-us/products/virtual-machines/',
    login_url: 'https://portal.azure.com/#blade/HubsExtension/BrowseResource/resourceType/Microsoft.Compute%2FVirtualMachines',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'custom',
  },
  {
    name: 'Azure Blob Storage',
    vendor: 'Microsoft Azure',
    category: 'infrastructure',
    icon: '🪣',
    description: 'Massively scalable object storage for unstructured data like documents, images, and videos.',
    features: 'Object storage, Hot/Cool/Archive tiers, Versioning, Lifecycle management, Static hosting, CDN integration',
    url: 'https://azure.microsoft.com/en-us/products/storage/blobs/',
    login_url: 'https://portal.azure.com/#blade/HubsExtension/BrowseResource/resourceType/Microsoft.Storage%2FStorageAccounts',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'custom',
  },
  {
    name: 'Azure App Service',
    vendor: 'Microsoft Azure',
    category: 'infrastructure',
    icon: '🚀',
    description: 'Fully managed platform for building, deploying, and scaling web apps and APIs.',
    features: 'PaaS hosting, Auto-scaling, Deployment slots, Custom domains, SSL certificates, CI/CD integration',
    url: 'https://azure.microsoft.com/en-us/products/app-service/',
    login_url: 'https://portal.azure.com/#blade/HubsExtension/BrowseResource/resourceType/Microsoft.Web%2Fsites',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'custom',
  },
  {
    name: 'Azure SQL Database',
    vendor: 'Microsoft Azure',
    category: 'infrastructure',
    icon: '🗄️',
    description: 'Fully managed relational database service with built-in intelligence and security.',
    features: 'Managed SQL Server, Auto-tuning, Geo-replication, Serverless option, Hyperscale, Advanced security',
    url: 'https://azure.microsoft.com/en-us/products/azure-sql/database/',
    login_url: 'https://portal.azure.com/#blade/HubsExtension/BrowseResource/resourceType/Microsoft.Sql%2Fservers%2Fdatabases',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'custom',
  },
  {
    name: 'Azure DevOps',
    vendor: 'Microsoft Azure',
    category: 'development',
    icon: '🔄',
    description: 'Development collaboration tools including repos, pipelines, boards, and artifacts.',
    features: 'Git repos, CI/CD pipelines, Kanban boards, Test plans, Artifacts, Wiki',
    url: 'https://azure.microsoft.com/en-us/products/devops/',
    login_url: 'https://dev.azure.com/',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },

  // ============ Google Cloud Services ============
  {
    name: 'Google Cloud Compute Engine',
    vendor: 'Google Cloud',
    category: 'infrastructure',
    icon: '🖥️',
    description: 'Scalable, high-performance virtual machines running in Google data centers.',
    features: 'Custom machine types, Preemptible VMs, Live migration, Persistent disks, GPU support, Sole-tenant nodes',
    url: 'https://cloud.google.com/compute',
    login_url: 'https://console.cloud.google.com/compute/instances',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'custom',
  },
  {
    name: 'Google Cloud Functions',
    vendor: 'Google Cloud',
    category: 'infrastructure',
    icon: '⚡',
    description: 'Serverless execution environment for building and connecting cloud services.',
    features: 'Serverless, Event-driven, Auto-scaling, Multiple runtimes, VPC connector, Cloud events',
    url: 'https://cloud.google.com/functions',
    login_url: 'https://console.cloud.google.com/functions',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'custom',
  },
  {
    name: 'Google Cloud Storage',
    vendor: 'Google Cloud',
    category: 'infrastructure',
    icon: '🪣',
    description: 'Unified object storage for developers and enterprises with global edge-caching.',
    features: 'Object storage, Multi-regional, Lifecycle management, Versioning, Strong consistency, CDN integration',
    url: 'https://cloud.google.com/storage',
    login_url: 'https://console.cloud.google.com/storage/browser',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'custom',
  },
  {
    name: 'Google Cloud Run',
    vendor: 'Google Cloud',
    category: 'infrastructure',
    icon: '🏃',
    description: 'Fully managed compute platform for running containerized applications.',
    features: 'Container hosting, Auto-scaling, Pay-per-use, Custom domains, Traffic splitting, Knative-based',
    url: 'https://cloud.google.com/run',
    login_url: 'https://console.cloud.google.com/run',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'custom',
  },
  {
    name: 'Firebase',
    vendor: 'Google',
    category: 'infrastructure',
    icon: '🔥',
    description: 'Platform for building mobile and web applications with real-time database and authentication.',
    features: 'Real-time database, Authentication, Cloud functions, Hosting, Analytics, Crashlytics',
    url: 'https://firebase.google.com/',
    login_url: 'https://console.firebase.google.com/',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'freemium',
  },

  // ============ Domain Registrars ============
  {
    name: 'Namecheap',
    vendor: 'Namecheap',
    category: 'infrastructure',
    icon: '🌐',
    description: 'Domain registrar and web hosting provider with competitive pricing and free privacy protection.',
    features: 'Domain registration, Free WHOIS privacy, DNS management, SSL certificates, Email hosting, Web hosting',
    url: 'https://www.namecheap.com/',
    login_url: 'https://www.namecheap.com/myaccount/login/',
    is_paid: true,
    billing_cycle: 'annually',
    license_type: 'custom',
  },
  {
    name: 'GoDaddy',
    vendor: 'GoDaddy',
    category: 'infrastructure',
    icon: '🌐',
    description: 'World\'s largest domain registrar with web hosting, website builder, and marketing tools.',
    features: 'Domain registration, Web hosting, Website builder, Email, SSL certificates, Marketing tools',
    url: 'https://www.godaddy.com/',
    login_url: 'https://sso.godaddy.com/',
    is_paid: true,
    billing_cycle: 'annually',
    license_type: 'custom',
  },
  {
    name: 'Cloudflare',
    vendor: 'Cloudflare',
    category: 'infrastructure',
    icon: '☁️',
    description: 'Web performance and security company providing CDN, DNS, DDoS protection, and domain registration.',
    features: 'CDN, DNS, DDoS protection, WAF, SSL/TLS, Workers, Pages, Domain registration, Zero Trust',
    url: 'https://www.cloudflare.com/',
    login_url: 'https://dash.cloudflare.com/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Google Domains',
    vendor: 'Google (now Squarespace)',
    category: 'infrastructure',
    icon: '🌐',
    description: 'Domain registration service with simple management and Google integration (now part of Squarespace).',
    features: 'Domain registration, DNS management, Email forwarding, WHOIS privacy, Google integration',
    url: 'https://domains.squarespace.com/',
    login_url: 'https://domains.squarespace.com/',
    is_paid: true,
    billing_cycle: 'annually',
    license_type: 'custom',
  },
  {
    name: 'Hover',
    vendor: 'Hover',
    category: 'infrastructure',
    icon: '🌐',
    description: 'Simple, no-upsell domain registration with free WHOIS privacy and email forwarding.',
    features: 'Domain registration, Free WHOIS privacy, Email forwarding, DNS management, Simple interface',
    url: 'https://www.hover.com/',
    login_url: 'https://www.hover.com/signin',
    is_paid: true,
    billing_cycle: 'annually',
    license_type: 'custom',
  },

  // ============ Hosting Platforms ============
  {
    name: 'Vercel',
    vendor: 'Vercel',
    category: 'infrastructure',
    icon: '▲',
    description: 'Platform for frontend frameworks and static sites with automatic deployments from Git.',
    features: 'Instant deployments, Preview URLs, Serverless functions, Edge network, Analytics, Next.js optimized',
    url: 'https://vercel.com/',
    login_url: 'https://vercel.com/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Netlify',
    vendor: 'Netlify',
    category: 'infrastructure',
    icon: '🔷',
    description: 'Platform for automating modern web projects with continuous deployment and serverless functions.',
    features: 'Continuous deployment, Serverless functions, Forms, Identity, Split testing, Edge handlers',
    url: 'https://www.netlify.com/',
    login_url: 'https://app.netlify.com/',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Heroku',
    vendor: 'Salesforce',
    category: 'infrastructure',
    icon: '🟣',
    description: 'Cloud platform as a service supporting multiple programming languages for app deployment.',
    features: 'PaaS hosting, Dynos, Add-ons marketplace, Pipelines, Review apps, Postgres, Redis',
    url: 'https://www.heroku.com/',
    login_url: 'https://id.heroku.com/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'DigitalOcean',
    vendor: 'DigitalOcean',
    category: 'infrastructure',
    icon: '🌊',
    description: 'Cloud infrastructure provider with simple, predictable pricing for developers and businesses.',
    features: 'Droplets, Kubernetes, App Platform, Managed databases, Spaces, Load balancers, VPC',
    url: 'https://www.digitalocean.com/',
    login_url: 'https://cloud.digitalocean.com/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'custom',
  },
  {
    name: 'Railway',
    vendor: 'Railway',
    category: 'infrastructure',
    icon: '🚂',
    description: 'Modern deployment platform for building and shipping applications with instant infrastructure.',
    features: 'Instant deployments, Databases, Private networking, Environments, Usage-based pricing, Templates',
    url: 'https://railway.app/',
    login_url: 'https://railway.app/login',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'freemium',
  },
  {
    name: 'Render',
    vendor: 'Render',
    category: 'infrastructure',
    icon: '🎨',
    description: 'Unified cloud to build and run all your apps and websites with free SSL and a global CDN.',
    features: 'Web services, Static sites, Cron jobs, Databases, Redis, Private services, Auto-deploy',
    url: 'https://render.com/',
    login_url: 'https://dashboard.render.com/',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },

  // ============ Development Tools ============
  {
    name: 'GitHub',
    vendor: 'Microsoft',
    category: 'development',
    icon: '🐙',
    description: 'Web-based platform for version control and collaboration using Git repositories.',
    features: 'Git hosting, Pull requests, Issues, Actions CI/CD, Codespaces, Copilot, Packages, Security',
    url: 'https://github.com/',
    login_url: 'https://github.com/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'GitLab',
    vendor: 'GitLab',
    category: 'development',
    icon: '🦊',
    description: 'Complete DevOps platform with source control, CI/CD, security, and project management.',
    features: 'Git hosting, CI/CD pipelines, Issue tracking, Code review, Security scanning, Container registry',
    url: 'https://gitlab.com/',
    login_url: 'https://gitlab.com/users/sign_in',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Bitbucket',
    vendor: 'Atlassian',
    category: 'development',
    icon: '🪣',
    description: 'Git repository management solution with Jira and Trello integration.',
    features: 'Git hosting, Pipelines CI/CD, Pull requests, Code review, Jira integration, Trello integration',
    url: 'https://bitbucket.org/',
    login_url: 'https://bitbucket.org/account/signin/',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Docker Hub',
    vendor: 'Docker',
    category: 'development',
    icon: '🐳',
    description: 'Container image registry for storing, sharing, and managing Docker container images.',
    features: 'Container registry, Official images, Automated builds, Webhooks, Teams, Vulnerability scanning',
    url: 'https://hub.docker.com/',
    login_url: 'https://login.docker.com/',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'npm',
    vendor: 'GitHub/Microsoft',
    category: 'development',
    icon: '📦',
    description: 'Package manager for JavaScript and the world\'s largest software registry.',
    features: 'Package hosting, Private packages, Teams, Security advisories, Provenance, Workspaces',
    url: 'https://www.npmjs.com/',
    login_url: 'https://www.npmjs.com/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'JetBrains',
    vendor: 'JetBrains',
    category: 'development',
    icon: '🧠',
    description: 'Professional IDE suite including IntelliJ IDEA, PyCharm, WebStorm, and more.',
    features: 'Smart code completion, Refactoring, Debugging, Version control, Database tools, AI assistant',
    url: 'https://www.jetbrains.com/',
    login_url: 'https://account.jetbrains.com/login',
    is_paid: true,
    billing_cycle: 'annually',
    license_type: 'pro',
  },
  {
    name: 'Postman',
    vendor: 'Postman',
    category: 'development',
    icon: '🚀',
    description: 'API platform for building, testing, documenting, and sharing APIs.',
    features: 'API testing, Collections, Environments, Mock servers, Documentation, Monitors, Flows',
    url: 'https://www.postman.com/',
    login_url: 'https://identity.getpostman.com/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },

  // ============ Communication ============
  {
    name: 'Slack',
    vendor: 'Salesforce',
    category: 'communication',
    icon: '💬',
    description: 'Business communication platform with channels, direct messaging, and app integrations.',
    features: 'Channels, Direct messages, Threads, File sharing, App integrations, Huddles, Workflows',
    url: 'https://slack.com/',
    login_url: 'https://slack.com/signin',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Discord',
    vendor: 'Discord',
    category: 'communication',
    icon: '🎮',
    description: 'Voice, video, and text communication platform originally for gamers, now used by communities.',
    features: 'Voice channels, Text channels, Screen sharing, Bots, Roles, Server templates, Stage channels',
    url: 'https://discord.com/',
    login_url: 'https://discord.com/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Microsoft Teams',
    vendor: 'Microsoft',
    category: 'communication',
    icon: '👥',
    description: 'Business communication and collaboration platform integrated with Microsoft 365.',
    features: 'Chat, Video calls, File sharing, Channels, Apps, Meetings, Webinars, Office integration',
    url: 'https://www.microsoft.com/en-us/microsoft-teams/',
    login_url: 'https://teams.microsoft.com/',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Zoom',
    vendor: 'Zoom',
    category: 'communication',
    icon: '📹',
    description: 'Video conferencing platform for meetings, webinars, and virtual events.',
    features: 'Video meetings, Webinars, Chat, Phone, Whiteboard, Breakout rooms, Recording, Virtual backgrounds',
    url: 'https://zoom.us/',
    login_url: 'https://zoom.us/signin',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Google Meet',
    vendor: 'Google',
    category: 'communication',
    icon: '📹',
    description: 'Video conferencing service integrated with Google Workspace.',
    features: 'Video meetings, Screen sharing, Live captions, Recording, Breakout rooms, Q&A, Polls',
    url: 'https://meet.google.com/',
    login_url: 'https://meet.google.com/',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },

  // ============ Email Services ============
  {
    name: 'Google Workspace',
    vendor: 'Google',
    category: 'communication',
    icon: '📧',
    description: 'Business productivity suite with Gmail, Drive, Docs, Calendar, and Meet.',
    features: 'Business email, Cloud storage, Docs/Sheets/Slides, Calendar, Meet, Admin console, Vault',
    url: 'https://workspace.google.com/',
    login_url: 'https://admin.google.com/',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'business',
  },
  {
    name: 'Microsoft 365',
    vendor: 'Microsoft',
    category: 'productivity',
    icon: '📧',
    description: 'Business productivity suite with Outlook, OneDrive, Word, Excel, and Teams.',
    features: 'Business email, OneDrive, Word/Excel/PowerPoint, Teams, SharePoint, Admin center, Security',
    url: 'https://www.microsoft.com/en-us/microsoft-365/business/',
    login_url: 'https://admin.microsoft.com/',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'business',
  },
  {
    name: 'SendGrid',
    vendor: 'Twilio',
    category: 'communication',
    icon: '📨',
    description: 'Cloud-based email delivery platform for transactional and marketing emails.',
    features: 'Email API, SMTP relay, Marketing campaigns, Templates, Analytics, Deliverability tools',
    url: 'https://sendgrid.com/',
    login_url: 'https://app.sendgrid.com/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Mailgun',
    vendor: 'Sinch',
    category: 'communication',
    icon: '📬',
    description: 'Email API service for sending, receiving, and tracking transactional emails.',
    features: 'Email API, SMTP, Inbound routing, Email validation, Analytics, Webhooks',
    url: 'https://www.mailgun.com/',
    login_url: 'https://login.mailgun.com/login/',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Resend',
    vendor: 'Resend',
    category: 'communication',
    icon: '✉️',
    description: 'Modern email API for developers with React Email support and excellent deliverability.',
    features: 'Email API, React Email, Webhooks, Analytics, Team management, Multiple domains',
    url: 'https://resend.com/',
    login_url: 'https://resend.com/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Postmark',
    vendor: 'ActiveCampaign',
    category: 'communication',
    icon: '📮',
    description: 'Transactional email service focused on deliverability and speed.',
    features: 'Transactional email, Templates, Message streams, Analytics, Webhooks, Inbound processing',
    url: 'https://postmarkapp.com/',
    login_url: 'https://account.postmarkapp.com/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'starter',
  },

  // ============ Productivity ============
  {
    name: 'Notion',
    vendor: 'Notion Labs',
    category: 'productivity',
    icon: '📝',
    description: 'All-in-one workspace for notes, docs, wikis, projects, and collaboration.',
    features: 'Notes, Docs, Wikis, Databases, Kanban, Calendar, Templates, API, AI assistant',
    url: 'https://www.notion.so/',
    login_url: 'https://www.notion.so/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Asana',
    vendor: 'Asana',
    category: 'productivity',
    icon: '✅',
    description: 'Work management platform for teams to organize, track, and manage work.',
    features: 'Tasks, Projects, Timeline, Boards, Portfolios, Goals, Automation, Reporting',
    url: 'https://asana.com/',
    login_url: 'https://app.asana.com/-/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Trello',
    vendor: 'Atlassian',
    category: 'productivity',
    icon: '📋',
    description: 'Visual collaboration tool using boards, lists, and cards for project management.',
    features: 'Boards, Lists, Cards, Power-Ups, Butler automation, Templates, Calendar view',
    url: 'https://trello.com/',
    login_url: 'https://trello.com/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Linear',
    vendor: 'Linear',
    category: 'productivity',
    icon: '📐',
    description: 'Modern issue tracking and project management tool built for software teams.',
    features: 'Issues, Cycles, Roadmaps, Projects, Triage, Git integration, Keyboard shortcuts, API',
    url: 'https://linear.app/',
    login_url: 'https://linear.app/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Jira',
    vendor: 'Atlassian',
    category: 'productivity',
    icon: '🔷',
    description: 'Issue and project tracking software for agile development teams.',
    features: 'Issues, Sprints, Kanban, Roadmaps, Reports, Automation, Integrations, Custom workflows',
    url: 'https://www.atlassian.com/software/jira',
    login_url: 'https://id.atlassian.com/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Monday.com',
    vendor: 'Monday.com',
    category: 'productivity',
    icon: '📊',
    description: 'Work operating system for managing projects, workflows, and team collaboration.',
    features: 'Boards, Dashboards, Automations, Integrations, Forms, Docs, Workload, Time tracking',
    url: 'https://monday.com/',
    login_url: 'https://auth.monday.com/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'starter',
  },
  {
    name: 'Confluence',
    vendor: 'Atlassian',
    category: 'productivity',
    icon: '📚',
    description: 'Team workspace for creating, organizing, and collaborating on documentation.',
    features: 'Pages, Spaces, Templates, Comments, Permissions, Macros, Jira integration, Search',
    url: 'https://www.atlassian.com/software/confluence',
    login_url: 'https://id.atlassian.com/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },

  // ============ Design ============
  {
    name: 'Figma',
    vendor: 'Figma (Adobe)',
    category: 'design',
    icon: '🎨',
    description: 'Collaborative interface design tool for creating UI/UX designs and prototypes.',
    features: 'Vector editing, Prototyping, Components, Auto layout, Plugins, Dev mode, FigJam',
    url: 'https://www.figma.com/',
    login_url: 'https://www.figma.com/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Canva',
    vendor: 'Canva',
    category: 'design',
    icon: '🖼️',
    description: 'Online graphic design platform with templates for social media, presentations, and more.',
    features: 'Templates, Brand kit, Magic resize, Background remover, Collaboration, Print, Video editor',
    url: 'https://www.canva.com/',
    login_url: 'https://www.canva.com/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Adobe Creative Cloud',
    vendor: 'Adobe',
    category: 'design',
    icon: '🎭',
    description: 'Suite of creative applications including Photoshop, Illustrator, Premiere Pro, and more.',
    features: 'Photoshop, Illustrator, Premiere Pro, After Effects, XD, Lightroom, Cloud storage, Fonts',
    url: 'https://www.adobe.com/creativecloud.html',
    login_url: 'https://account.adobe.com/',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'pro',
  },

  // ============ Analytics ============
  {
    name: 'Google Analytics',
    vendor: 'Google',
    category: 'analytics',
    icon: '📈',
    description: 'Web analytics service tracking and reporting website traffic and user behavior.',
    features: 'Traffic analysis, Audience insights, Conversions, Real-time data, Custom reports, BigQuery export',
    url: 'https://analytics.google.com/',
    login_url: 'https://analytics.google.com/',
    is_paid: false,
    billing_cycle: '',
    license_type: 'free',
  },
  {
    name: 'Mixpanel',
    vendor: 'Mixpanel',
    category: 'analytics',
    icon: '📊',
    description: 'Product analytics platform for tracking user interactions and behavior.',
    features: 'Event tracking, Funnels, Retention, Cohorts, A/B testing, User profiles, Alerts',
    url: 'https://mixpanel.com/',
    login_url: 'https://mixpanel.com/login/',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Amplitude',
    vendor: 'Amplitude',
    category: 'analytics',
    icon: '📉',
    description: 'Digital analytics platform for understanding user behavior and product growth.',
    features: 'Behavioral analytics, Cohorts, Funnels, Pathfinder, Experiments, Audiences, CDP',
    url: 'https://amplitude.com/',
    login_url: 'https://analytics.amplitude.com/',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Hotjar',
    vendor: 'Contentsquare',
    category: 'analytics',
    icon: '🔥',
    description: 'Behavior analytics and feedback tool with heatmaps and session recordings.',
    features: 'Heatmaps, Session recordings, Surveys, Feedback widgets, Funnels, User interviews',
    url: 'https://www.hotjar.com/',
    login_url: 'https://insights.hotjar.com/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'PostHog',
    vendor: 'PostHog',
    category: 'analytics',
    icon: '🦔',
    description: 'Open-source product analytics platform with feature flags and session replay.',
    features: 'Event analytics, Session replay, Feature flags, A/B testing, Surveys, Data warehouse',
    url: 'https://posthog.com/',
    login_url: 'https://app.posthog.com/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },

  // ============ Payments ============
  {
    name: 'Stripe',
    vendor: 'Stripe',
    category: 'finance',
    icon: '💳',
    description: 'Online payment processing platform for internet businesses.',
    features: 'Payments, Subscriptions, Invoicing, Connect, Radar fraud, Terminal, Atlas, Tax',
    url: 'https://stripe.com/',
    login_url: 'https://dashboard.stripe.com/login',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'custom',
  },
  {
    name: 'PayPal',
    vendor: 'PayPal',
    category: 'finance',
    icon: '💰',
    description: 'Online payments system for sending and receiving money and accepting payments.',
    features: 'Payments, Invoicing, Pay Later, Business account, Mass payments, Subscriptions',
    url: 'https://www.paypal.com/',
    login_url: 'https://www.paypal.com/signin',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'custom',
  },
  {
    name: 'Square',
    vendor: 'Block',
    category: 'finance',
    icon: '⬜',
    description: 'Financial services and digital payments company with POS and online payments.',
    features: 'POS, Online payments, Invoicing, Payroll, Banking, Appointments, Loyalty',
    url: 'https://squareup.com/',
    login_url: 'https://squareup.com/login',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'custom',
  },

  // ============ Marketing ============
  {
    name: 'Mailchimp',
    vendor: 'Intuit',
    category: 'marketing',
    icon: '🐵',
    description: 'Marketing automation platform for email campaigns, landing pages, and audience management.',
    features: 'Email campaigns, Automations, Landing pages, Audience management, Analytics, A/B testing',
    url: 'https://mailchimp.com/',
    login_url: 'https://login.mailchimp.com/',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'HubSpot',
    vendor: 'HubSpot',
    category: 'marketing',
    icon: '🧡',
    description: 'CRM platform with marketing, sales, service, and content management tools.',
    features: 'CRM, Marketing automation, Sales pipeline, Service desk, CMS, Analytics, AI',
    url: 'https://www.hubspot.com/',
    login_url: 'https://app.hubspot.com/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'ConvertKit',
    vendor: 'ConvertKit',
    category: 'marketing',
    icon: '✉️',
    description: 'Email marketing platform designed for creators with automations and landing pages.',
    features: 'Email sequences, Automations, Landing pages, Forms, Subscriber tagging, Commerce',
    url: 'https://convertkit.com/',
    login_url: 'https://app.convertkit.com/users/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },

  // ============ Security ============
  {
    name: '1Password',
    vendor: '1Password',
    category: 'security',
    icon: '🔐',
    description: 'Password manager for teams and families with secure credential sharing.',
    features: 'Password vault, Secure sharing, Watchtower, Travel mode, SSO, CLI, Browser extension',
    url: 'https://1password.com/',
    login_url: 'https://my.1password.com/signin',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'business',
  },
  {
    name: 'LastPass',
    vendor: 'LastPass',
    category: 'security',
    icon: '🔒',
    description: 'Password manager with secure vault, password generator, and team features.',
    features: 'Password vault, Auto-fill, Password generator, Secure notes, Dark web monitoring, SSO',
    url: 'https://www.lastpass.com/',
    login_url: 'https://lastpass.com/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Auth0',
    vendor: 'Okta',
    category: 'security',
    icon: '🛡️',
    description: 'Identity platform for authentication and authorization with universal login.',
    features: 'Universal login, SSO, MFA, Social login, User management, Rules, Actions',
    url: 'https://auth0.com/',
    login_url: 'https://manage.auth0.com/',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Okta',
    vendor: 'Okta',
    category: 'security',
    icon: '🔑',
    description: 'Enterprise identity and access management platform with SSO and MFA.',
    features: 'SSO, MFA, Lifecycle management, API access, Universal directory, Workflows',
    url: 'https://www.okta.com/',
    login_url: 'https://login.okta.com/',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'enterprise',
  },

  // ============ Monitoring ============
  {
    name: 'Datadog',
    vendor: 'Datadog',
    category: 'analytics',
    icon: '🐕',
    description: 'Monitoring and analytics platform for cloud-scale applications and infrastructure.',
    features: 'Infrastructure monitoring, APM, Logs, RUM, Synthetics, Security, Dashboards',
    url: 'https://www.datadoghq.com/',
    login_url: 'https://app.datadoghq.com/',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'custom',
  },
  {
    name: 'Sentry',
    vendor: 'Sentry',
    category: 'development',
    icon: '🐛',
    description: 'Application monitoring and error tracking platform for developers.',
    features: 'Error tracking, Performance monitoring, Session replay, Profiling, Crons, Releases',
    url: 'https://sentry.io/',
    login_url: 'https://sentry.io/auth/login/',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'New Relic',
    vendor: 'New Relic',
    category: 'analytics',
    icon: '📊',
    description: 'Observability platform for monitoring applications, infrastructure, and logs.',
    features: 'APM, Infrastructure, Logs, Browser, Synthetics, Mobile, Alerts, Dashboards',
    url: 'https://newrelic.com/',
    login_url: 'https://login.newrelic.com/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'PagerDuty',
    vendor: 'PagerDuty',
    category: 'productivity',
    icon: '🚨',
    description: 'Incident management platform for real-time operations and on-call scheduling.',
    features: 'Incident response, On-call scheduling, Escalation policies, Integrations, Analytics, Automation',
    url: 'https://www.pagerduty.com/',
    login_url: 'https://app.pagerduty.com/',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'pro',
  },

  // ============ AI/ML ============
  {
    name: 'OpenAI',
    vendor: 'OpenAI',
    category: 'development',
    icon: '🤖',
    description: 'AI research company providing GPT models, DALL-E, and other AI APIs.',
    features: 'GPT-4, ChatGPT, DALL-E, Whisper, Embeddings, Fine-tuning, Assistants API',
    url: 'https://openai.com/',
    login_url: 'https://platform.openai.com/login',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'custom',
  },
  {
    name: 'Anthropic Claude',
    vendor: 'Anthropic',
    category: 'development',
    icon: '🧠',
    description: 'AI assistant and API providing Claude models for various AI applications.',
    features: 'Claude models, API access, Long context, Vision, Tool use, Constitutional AI',
    url: 'https://www.anthropic.com/',
    login_url: 'https://console.anthropic.com/',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'custom',
  },
  {
    name: 'Hugging Face',
    vendor: 'Hugging Face',
    category: 'development',
    icon: '🤗',
    description: 'AI community platform with model hub, datasets, and inference endpoints.',
    features: 'Model hub, Datasets, Spaces, Inference API, AutoTrain, Transformers library',
    url: 'https://huggingface.co/',
    login_url: 'https://huggingface.co/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },

  // ============ More AWS Services ============
  {
    name: 'AWS DynamoDB',
    vendor: 'Amazon Web Services',
    category: 'infrastructure',
    icon: '⚡',
    description: 'Fully managed NoSQL database service with single-digit millisecond performance.',
    features: 'NoSQL, Auto-scaling, Global tables, Streams, DAX caching, On-demand capacity',
    url: 'https://aws.amazon.com/dynamodb/',
    login_url: 'https://console.aws.amazon.com/dynamodb/',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'custom',
  },
  {
    name: 'AWS SNS',
    vendor: 'Amazon Web Services',
    category: 'infrastructure',
    icon: '📢',
    description: 'Simple Notification Service for pub/sub messaging and mobile push notifications.',
    features: 'Pub/Sub, SMS, Push notifications, Email, HTTP webhooks, Message filtering',
    url: 'https://aws.amazon.com/sns/',
    login_url: 'https://console.aws.amazon.com/sns/',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'custom',
  },
  {
    name: 'AWS SQS',
    vendor: 'Amazon Web Services',
    category: 'infrastructure',
    icon: '📬',
    description: 'Simple Queue Service for decoupling and scaling microservices and applications.',
    features: 'Message queues, FIFO queues, Dead letter queues, Long polling, Encryption',
    url: 'https://aws.amazon.com/sqs/',
    login_url: 'https://console.aws.amazon.com/sqs/',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'custom',
  },
  {
    name: 'AWS Cognito',
    vendor: 'Amazon Web Services',
    category: 'security',
    icon: '🔐',
    description: 'User authentication and authorization service for web and mobile apps.',
    features: 'User pools, Identity pools, Social login, MFA, OAuth/OIDC, Lambda triggers',
    url: 'https://aws.amazon.com/cognito/',
    login_url: 'https://console.aws.amazon.com/cognito/',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'custom',
  },
  {
    name: 'AWS ECS',
    vendor: 'Amazon Web Services',
    category: 'infrastructure',
    icon: '🐳',
    description: 'Elastic Container Service for running Docker containers at scale.',
    features: 'Container orchestration, Fargate serverless, EC2 launch type, Service discovery, Load balancing',
    url: 'https://aws.amazon.com/ecs/',
    login_url: 'https://console.aws.amazon.com/ecs/',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'custom',
  },
  {
    name: 'AWS EKS',
    vendor: 'Amazon Web Services',
    category: 'infrastructure',
    icon: '☸️',
    description: 'Elastic Kubernetes Service for running Kubernetes clusters on AWS.',
    features: 'Managed Kubernetes, Fargate, Auto-scaling, IAM integration, VPC networking',
    url: 'https://aws.amazon.com/eks/',
    login_url: 'https://console.aws.amazon.com/eks/',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'custom',
  },
  {
    name: 'AWS Secrets Manager',
    vendor: 'Amazon Web Services',
    category: 'security',
    icon: '🔑',
    description: 'Secrets management service for rotating, managing, and retrieving credentials.',
    features: 'Secret rotation, RDS integration, Cross-account access, Encryption, Versioning',
    url: 'https://aws.amazon.com/secrets-manager/',
    login_url: 'https://console.aws.amazon.com/secretsmanager/',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'custom',
  },
  {
    name: 'AWS IAM',
    vendor: 'Amazon Web Services',
    category: 'security',
    icon: '👤',
    description: 'Identity and Access Management for secure access control to AWS services.',
    features: 'Users, Groups, Roles, Policies, MFA, Identity federation, Access analyzer',
    url: 'https://aws.amazon.com/iam/',
    login_url: 'https://console.aws.amazon.com/iam/',
    is_paid: false,
    billing_cycle: '',
    license_type: 'free',
  },
  {
    name: 'AWS CloudWatch',
    vendor: 'Amazon Web Services',
    category: 'analytics',
    icon: '📊',
    description: 'Monitoring and observability service for AWS resources and applications.',
    features: 'Metrics, Logs, Alarms, Dashboards, Events, Insights, Synthetics',
    url: 'https://aws.amazon.com/cloudwatch/',
    login_url: 'https://console.aws.amazon.com/cloudwatch/',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'custom',
  },
  {
    name: 'AWS Amplify',
    vendor: 'Amazon Web Services',
    category: 'development',
    icon: '📱',
    description: 'Full-stack development platform for building web and mobile applications.',
    features: 'Hosting, Auth, Storage, API, Functions, Analytics, CI/CD, Studio',
    url: 'https://aws.amazon.com/amplify/',
    login_url: 'https://console.aws.amazon.com/amplify/',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'freemium',
  },

  // ============ Accounting & Finance ============
  {
    name: 'QuickBooks Online',
    vendor: 'Intuit',
    category: 'finance',
    icon: '📗',
    description: 'Cloud accounting software for small businesses with invoicing, expenses, and reporting.',
    features: 'Invoicing, Expense tracking, Bank feeds, Payroll, Reports, Tax prep, Inventory',
    url: 'https://quickbooks.intuit.com/',
    login_url: 'https://accounts.intuit.com/',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'business',
  },
  {
    name: 'Xero',
    vendor: 'Xero',
    category: 'finance',
    icon: '💙',
    description: 'Cloud-based accounting software for small and medium businesses.',
    features: 'Invoicing, Bank reconciliation, Payroll, Projects, Expenses, Reports, Multi-currency',
    url: 'https://www.xero.com/',
    login_url: 'https://login.xero.com/',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'business',
  },
  {
    name: 'FreshBooks',
    vendor: 'FreshBooks',
    category: 'finance',
    icon: '🌿',
    description: 'Accounting software designed for small business owners and freelancers.',
    features: 'Invoicing, Time tracking, Expenses, Projects, Estimates, Payments, Reports',
    url: 'https://www.freshbooks.com/',
    login_url: 'https://my.freshbooks.com/',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'starter',
  },
  {
    name: 'Wave',
    vendor: 'Wave Financial',
    category: 'finance',
    icon: '🌊',
    description: 'Free accounting and invoicing software for small businesses.',
    features: 'Invoicing, Accounting, Receipts, Payments, Payroll, Reports, Bank connections',
    url: 'https://www.waveapps.com/',
    login_url: 'https://my.waveapps.com/login/',
    is_paid: false,
    billing_cycle: '',
    license_type: 'free',
  },
  {
    name: 'Zoho Books',
    vendor: 'Zoho',
    category: 'finance',
    icon: '📘',
    description: 'Online accounting software for managing finances and automating business workflows.',
    features: 'Invoicing, Expenses, Banking, Inventory, Projects, Time tracking, Reports',
    url: 'https://www.zoho.com/books/',
    login_url: 'https://accounts.zoho.com/signin',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Gusto',
    vendor: 'Gusto',
    category: 'hr',
    icon: '💚',
    description: 'All-in-one HR platform for payroll, benefits, and team management.',
    features: 'Payroll, Benefits, HR tools, Time tracking, Onboarding, Compliance, 401(k)',
    url: 'https://gusto.com/',
    login_url: 'https://app.gusto.com/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'business',
  },
  {
    name: 'Rippling',
    vendor: 'Rippling',
    category: 'hr',
    icon: '🌀',
    description: 'Unified workforce platform for HR, IT, and Finance operations.',
    features: 'Payroll, Benefits, Device management, App management, Time tracking, Learning',
    url: 'https://www.rippling.com/',
    login_url: 'https://app.rippling.com/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'business',
  },
  {
    name: 'BambooHR',
    vendor: 'BambooHR',
    category: 'hr',
    icon: '🎋',
    description: 'HR software for hiring, onboarding, compensation, and culture.',
    features: 'Employee records, Onboarding, Time off, Performance, Reporting, ATS, Payroll',
    url: 'https://www.bamboohr.com/',
    login_url: 'https://www.bamboohr.com/login/',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'business',
  },
  {
    name: 'Deel',
    vendor: 'Deel',
    category: 'hr',
    icon: '🌍',
    description: 'Global payroll and compliance platform for hiring international teams.',
    features: 'Global payroll, Contractors, EOR, Compliance, Payments, HR, Immigration',
    url: 'https://www.deel.com/',
    login_url: 'https://app.deel.com/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'custom',
  },
  {
    name: 'Mercury',
    vendor: 'Mercury',
    category: 'finance',
    icon: '🪐',
    description: 'Banking for startups with checking, savings, and treasury services.',
    features: 'Business checking, Savings, Treasury, Cards, Payments, API, Integrations',
    url: 'https://mercury.com/',
    login_url: 'https://app.mercury.com/login',
    is_paid: false,
    billing_cycle: '',
    license_type: 'free',
  },
  {
    name: 'Brex',
    vendor: 'Brex',
    category: 'finance',
    icon: '💳',
    description: 'Corporate card and spend management platform for startups and enterprises.',
    features: 'Corporate cards, Expense management, Bill pay, Travel, Rewards, Controls',
    url: 'https://www.brex.com/',
    login_url: 'https://dashboard.brex.com/',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Ramp',
    vendor: 'Ramp',
    category: 'finance',
    icon: '📈',
    description: 'Corporate card and finance automation platform that helps companies save money.',
    features: 'Corporate cards, Expense management, Bill pay, Accounting automation, Savings insights',
    url: 'https://ramp.com/',
    login_url: 'https://app.ramp.com/sign-in',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Expensify',
    vendor: 'Expensify',
    category: 'finance',
    icon: '🧾',
    description: 'Expense management and reporting software with receipt scanning.',
    features: 'Receipt scanning, Expense reports, Corporate cards, Bill pay, Travel, Accounting sync',
    url: 'https://www.expensify.com/',
    login_url: 'https://www.expensify.com/signin',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },

  // ============ Customer Support ============
  {
    name: 'Zendesk',
    vendor: 'Zendesk',
    category: 'communication',
    icon: '🎧',
    description: 'Customer service software for support ticketing, chat, and knowledge base.',
    features: 'Ticketing, Live chat, Help center, AI, Analytics, Integrations, Omnichannel',
    url: 'https://www.zendesk.com/',
    login_url: 'https://www.zendesk.com/login/',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'pro',
  },
  {
    name: 'Intercom',
    vendor: 'Intercom',
    category: 'communication',
    icon: '💬',
    description: 'Customer messaging platform with chat, bots, and help desk.',
    features: 'Live chat, Chatbots, Help desk, Product tours, Outbound messaging, AI',
    url: 'https://www.intercom.com/',
    login_url: 'https://app.intercom.com/',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'starter',
  },
  {
    name: 'Freshdesk',
    vendor: 'Freshworks',
    category: 'communication',
    icon: '🎫',
    description: 'Customer support software with ticketing, self-service, and AI.',
    features: 'Ticketing, Knowledge base, Chat, Phone, AI, Automations, Reports',
    url: 'https://freshdesk.com/',
    login_url: 'https://freshdesk.com/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Help Scout',
    vendor: 'Help Scout',
    category: 'communication',
    icon: '📨',
    description: 'Help desk software with shared inboxes and knowledge base.',
    features: 'Shared inbox, Knowledge base, Live chat, Reports, Workflows, Integrations',
    url: 'https://www.helpscout.com/',
    login_url: 'https://secure.helpscout.net/',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'starter',
  },
  {
    name: 'Crisp',
    vendor: 'Crisp',
    category: 'communication',
    icon: '💭',
    description: 'Business messaging platform with live chat, chatbot, and shared inbox.',
    features: 'Live chat, Chatbot, Shared inbox, Knowledge base, CRM, Campaigns',
    url: 'https://crisp.chat/',
    login_url: 'https://app.crisp.chat/initiate/login/',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },

  // ============ CRM ============
  {
    name: 'Salesforce',
    vendor: 'Salesforce',
    category: 'marketing',
    icon: '☁️',
    description: 'Enterprise CRM platform for sales, service, marketing, and commerce.',
    features: 'Sales Cloud, Service Cloud, Marketing Cloud, Commerce, Analytics, AppExchange',
    url: 'https://www.salesforce.com/',
    login_url: 'https://login.salesforce.com/',
    is_paid: true,
    billing_cycle: 'annually',
    license_type: 'enterprise',
  },
  {
    name: 'Pipedrive',
    vendor: 'Pipedrive',
    category: 'marketing',
    icon: '🔵',
    description: 'Sales CRM and pipeline management software designed for small teams.',
    features: 'Pipeline management, Activity tracking, Email integration, Reporting, Automation, AI',
    url: 'https://www.pipedrive.com/',
    login_url: 'https://app.pipedrive.com/auth/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'starter',
  },
  {
    name: 'Zoho CRM',
    vendor: 'Zoho',
    category: 'marketing',
    icon: '🟡',
    description: 'CRM software for managing sales, marketing, and support in a single platform.',
    features: 'Leads, Deals, Contacts, Email, Automation, Analytics, AI, Integrations',
    url: 'https://www.zoho.com/crm/',
    login_url: 'https://accounts.zoho.com/signin',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Close',
    vendor: 'Close',
    category: 'marketing',
    icon: '📞',
    description: 'CRM built for sales teams with built-in calling, email, and SMS.',
    features: 'Pipeline, Built-in calling, Email sequences, SMS, Reporting, Power dialer',
    url: 'https://www.close.com/',
    login_url: 'https://app.close.com/',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'starter',
  },
  {
    name: 'Copper',
    vendor: 'Copper',
    category: 'marketing',
    icon: '🟠',
    description: 'CRM that works natively with Google Workspace for relationship management.',
    features: 'Google Workspace native, Pipeline, Email tracking, Automation, Reports',
    url: 'https://www.copper.com/',
    login_url: 'https://app.copper.com/',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'starter',
  },

  // ============ E-commerce ============
  {
    name: 'Shopify',
    vendor: 'Shopify',
    category: 'marketing',
    icon: '🛒',
    description: 'E-commerce platform for online stores, retail POS, and social selling.',
    features: 'Online store, POS, Payments, Shipping, Marketing, Analytics, App store',
    url: 'https://www.shopify.com/',
    login_url: 'https://accounts.shopify.com/lookup',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'starter',
  },
  {
    name: 'WooCommerce',
    vendor: 'Automattic',
    category: 'marketing',
    icon: '🟣',
    description: 'Open-source e-commerce plugin for WordPress websites.',
    features: 'WordPress integration, Extensions, Payments, Shipping, Tax, Inventory',
    url: 'https://woocommerce.com/',
    login_url: 'https://woocommerce.com/my-account/',
    is_paid: true,
    billing_cycle: 'annually',
    license_type: 'freemium',
  },
  {
    name: 'BigCommerce',
    vendor: 'BigCommerce',
    category: 'marketing',
    icon: '🛍️',
    description: 'E-commerce platform for building online stores with omnichannel selling.',
    features: 'Online store, Multi-channel, B2B, Headless, SEO, Payments, Shipping',
    url: 'https://www.bigcommerce.com/',
    login_url: 'https://login.bigcommerce.com/',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'pro',
  },
  {
    name: 'Gumroad',
    vendor: 'Gumroad',
    category: 'finance',
    icon: '🎨',
    description: 'Platform for creators to sell digital products, memberships, and more.',
    features: 'Digital products, Memberships, Payments, Email, Analytics, Workflows',
    url: 'https://gumroad.com/',
    login_url: 'https://app.gumroad.com/login',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'freemium',
  },
  {
    name: 'Lemonsqueezy',
    vendor: 'Lemonsqueezy',
    category: 'finance',
    icon: '🍋',
    description: 'All-in-one platform for selling digital products with payments and tax handling.',
    features: 'Digital products, Subscriptions, License keys, Global tax, Affiliate, Checkout',
    url: 'https://www.lemonsqueezy.com/',
    login_url: 'https://app.lemonsqueezy.com/login',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'freemium',
  },

  // ============ Legal & Contracts ============
  {
    name: 'DocuSign',
    vendor: 'DocuSign',
    category: 'productivity',
    icon: '✍️',
    description: 'Electronic signature and agreement cloud for digital transactions.',
    features: 'E-signatures, Templates, Workflows, Mobile signing, Integrations, CLM',
    url: 'https://www.docusign.com/',
    login_url: 'https://account.docusign.com/',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'starter',
  },
  {
    name: 'HelloSign',
    vendor: 'Dropbox',
    category: 'productivity',
    icon: '📝',
    description: 'E-signature solution for getting documents signed quickly and securely.',
    features: 'E-signatures, Templates, Team management, API, Audit trail, Integrations',
    url: 'https://www.hellosign.com/',
    login_url: 'https://app.hellosign.com/account/logIn',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'PandaDoc',
    vendor: 'PandaDoc',
    category: 'productivity',
    icon: '🐼',
    description: 'Document automation software for proposals, quotes, and contracts.',
    features: 'Documents, E-signatures, Templates, CRM integration, Payments, Analytics',
    url: 'https://www.pandadoc.com/',
    login_url: 'https://app.pandadoc.com/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Clerky',
    vendor: 'Clerky',
    category: 'productivity',
    icon: '⚖️',
    description: 'Legal software for startups to handle incorporation and fundraising paperwork.',
    features: 'Incorporation, Fundraising docs, Hiring docs, Equity, Board consents',
    url: 'https://www.clerky.com/',
    login_url: 'https://www.clerky.com/login',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'custom',
  },

  // ============ Scheduling & Calendar ============
  {
    name: 'Calendly',
    vendor: 'Calendly',
    category: 'productivity',
    icon: '📅',
    description: 'Scheduling automation platform for booking meetings without the back-and-forth.',
    features: 'Scheduling links, Team scheduling, Integrations, Workflows, Analytics, Routing',
    url: 'https://calendly.com/',
    login_url: 'https://calendly.com/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Cal.com',
    vendor: 'Cal.com',
    category: 'productivity',
    icon: '📆',
    description: 'Open-source scheduling infrastructure for everyone.',
    features: 'Scheduling, Team features, Workflows, Routing, API, Self-hosting option',
    url: 'https://cal.com/',
    login_url: 'https://app.cal.com/auth/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'SavvyCal',
    vendor: 'SavvyCal',
    category: 'productivity',
    icon: '🗓️',
    description: 'Scheduling tool that makes finding meeting times more personalized.',
    features: 'Overlay calendars, Scheduling links, Time zone detection, Integrations',
    url: 'https://savvycal.com/',
    login_url: 'https://savvycal.com/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'starter',
  },

  // ============ Video & Screen Recording ============
  {
    name: 'Loom',
    vendor: 'Atlassian',
    category: 'communication',
    icon: '🎥',
    description: 'Video messaging platform for recording and sharing screen recordings.',
    features: 'Screen recording, Webcam, Transcripts, Comments, Analytics, Integrations',
    url: 'https://www.loom.com/',
    login_url: 'https://www.loom.com/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Riverside',
    vendor: 'Riverside.fm',
    category: 'communication',
    icon: '🎙️',
    description: 'Recording studio for podcasts and video with local recording quality.',
    features: 'Podcast recording, Video recording, Local quality, Transcription, Editing',
    url: 'https://riverside.fm/',
    login_url: 'https://riverside.fm/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Descript',
    vendor: 'Descript',
    category: 'design',
    icon: '✂️',
    description: 'All-in-one video and podcast editing with transcription-based editing.',
    features: 'Video editing, Podcast editing, Transcription, Screen recording, AI voices, Overdub',
    url: 'https://www.descript.com/',
    login_url: 'https://web.descript.com/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },

  // ============ Social Media Management ============
  {
    name: 'Buffer',
    vendor: 'Buffer',
    category: 'marketing',
    icon: '📱',
    description: 'Social media management platform for scheduling and publishing content.',
    features: 'Scheduling, Publishing, Analytics, Engagement, Start Page, AI assistant',
    url: 'https://buffer.com/',
    login_url: 'https://login.buffer.com/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Hootsuite',
    vendor: 'Hootsuite',
    category: 'marketing',
    icon: '🦉',
    description: 'Social media management platform for scheduling, monitoring, and analytics.',
    features: 'Scheduling, Monitoring, Analytics, Team collaboration, Content curation, Ads',
    url: 'https://www.hootsuite.com/',
    login_url: 'https://hootsuite.com/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'pro',
  },
  {
    name: 'Sprout Social',
    vendor: 'Sprout Social',
    category: 'marketing',
    icon: '🌱',
    description: 'Social media management and intelligence platform for businesses.',
    features: 'Publishing, Engagement, Analytics, Listening, Advocacy, Premium analytics',
    url: 'https://sproutsocial.com/',
    login_url: 'https://app.sproutsocial.com/login/',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'pro',
  },
  {
    name: 'Later',
    vendor: 'Later',
    category: 'marketing',
    icon: '📸',
    description: 'Social media scheduling platform with visual content calendar.',
    features: 'Visual planner, Scheduling, Link in bio, Analytics, User-generated content',
    url: 'https://later.com/',
    login_url: 'https://app.later.com/users/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },

  // ============ SEO & Content ============
  {
    name: 'Ahrefs',
    vendor: 'Ahrefs',
    category: 'marketing',
    icon: '🔗',
    description: 'SEO toolset for backlink analysis, keyword research, and site audits.',
    features: 'Site explorer, Keywords explorer, Site audit, Rank tracker, Content explorer',
    url: 'https://ahrefs.com/',
    login_url: 'https://app.ahrefs.com/user/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'pro',
  },
  {
    name: 'Semrush',
    vendor: 'Semrush',
    category: 'marketing',
    icon: '📊',
    description: 'All-in-one digital marketing platform for SEO, content, and competitive research.',
    features: 'SEO, Content marketing, Competitor analysis, PPC, Social media, Local SEO',
    url: 'https://www.semrush.com/',
    login_url: 'https://www.semrush.com/login/',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'pro',
  },
  {
    name: 'Moz',
    vendor: 'Moz',
    category: 'marketing',
    icon: '🟦',
    description: 'SEO software for improving search engine visibility and rankings.',
    features: 'Keyword research, Link analysis, Site audits, Rank tracking, On-page optimization',
    url: 'https://moz.com/',
    login_url: 'https://moz.com/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'pro',
  },
  {
    name: 'Surfer SEO',
    vendor: 'Surfer',
    category: 'marketing',
    icon: '🏄',
    description: 'Content optimization tool for ranking higher in search results.',
    features: 'Content editor, SERP analyzer, Keyword research, Audit, AI writing, Grow Flow',
    url: 'https://surferseo.com/',
    login_url: 'https://app.surferseo.com/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'pro',
  },

  // ============ Advertising ============
  {
    name: 'Google Ads',
    vendor: 'Google',
    category: 'marketing',
    icon: '🎯',
    description: 'Online advertising platform for search, display, video, and app campaigns.',
    features: 'Search ads, Display ads, Video ads, Shopping ads, App ads, Performance Max',
    url: 'https://ads.google.com/',
    login_url: 'https://ads.google.com/',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'custom',
  },
  {
    name: 'Meta Ads',
    vendor: 'Meta',
    category: 'marketing',
    icon: '📘',
    description: 'Advertising platform for Facebook, Instagram, Messenger, and WhatsApp.',
    features: 'Feed ads, Stories, Reels, Audience targeting, Conversions API, Catalog ads',
    url: 'https://www.facebook.com/business/ads',
    login_url: 'https://business.facebook.com/',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'custom',
  },
  {
    name: 'LinkedIn Ads',
    vendor: 'Microsoft',
    category: 'marketing',
    icon: '💼',
    description: 'B2B advertising platform for reaching professionals on LinkedIn.',
    features: 'Sponsored content, Message ads, Dynamic ads, Text ads, Lead gen forms',
    url: 'https://business.linkedin.com/marketing-solutions/ads',
    login_url: 'https://www.linkedin.com/campaignmanager/',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'custom',
  },

  // ============ Testing & QA ============
  {
    name: 'BrowserStack',
    vendor: 'BrowserStack',
    category: 'development',
    icon: '🌐',
    description: 'Cloud testing platform for web and mobile app testing on real devices.',
    features: 'Live testing, Automated testing, Real devices, Screenshots, Responsive testing',
    url: 'https://www.browserstack.com/',
    login_url: 'https://www.browserstack.com/users/sign_in',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'pro',
  },
  {
    name: 'Cypress',
    vendor: 'Cypress.io',
    category: 'development',
    icon: '🌲',
    description: 'JavaScript end-to-end testing framework for modern web applications.',
    features: 'E2E testing, Component testing, Real-time reloads, Time travel debugging, CI integration',
    url: 'https://www.cypress.io/',
    login_url: 'https://cloud.cypress.io/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Playwright',
    vendor: 'Microsoft',
    category: 'development',
    icon: '🎭',
    description: 'End-to-end testing framework for modern web apps across all browsers.',
    features: 'Cross-browser, Auto-wait, Mobile emulation, Codegen, Trace viewer, API testing',
    url: 'https://playwright.dev/',
    login_url: '',
    is_paid: false,
    billing_cycle: '',
    license_type: 'free',
  },

  // ============ Database Services ============
  {
    name: 'MongoDB Atlas',
    vendor: 'MongoDB',
    category: 'infrastructure',
    icon: '🍃',
    description: 'Fully managed cloud database service for MongoDB.',
    features: 'Document database, Auto-scaling, Global clusters, Charts, Search, Realm sync',
    url: 'https://www.mongodb.com/atlas',
    login_url: 'https://account.mongodb.com/account/login',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'freemium',
  },
  {
    name: 'PlanetScale',
    vendor: 'PlanetScale',
    category: 'infrastructure',
    icon: '🪐',
    description: 'Serverless MySQL platform with branching and non-blocking schema changes.',
    features: 'MySQL compatible, Branching, Deploy requests, Insights, Boost caching',
    url: 'https://planetscale.com/',
    login_url: 'https://auth.planetscale.com/sign-in',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'freemium',
  },
  {
    name: 'Supabase',
    vendor: 'Supabase',
    category: 'infrastructure',
    icon: '⚡',
    description: 'Open-source Firebase alternative with Postgres database and auth.',
    features: 'Postgres, Auth, Storage, Edge functions, Realtime, Vector embeddings',
    url: 'https://supabase.com/',
    login_url: 'https://supabase.com/dashboard/sign-in',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Neon',
    vendor: 'Neon',
    category: 'infrastructure',
    icon: '🌙',
    description: 'Serverless Postgres with branching, autoscaling, and bottomless storage.',
    features: 'Serverless Postgres, Branching, Auto-scaling, Bottomless storage, Connection pooling',
    url: 'https://neon.tech/',
    login_url: 'https://console.neon.tech/',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'freemium',
  },
  {
    name: 'Upstash',
    vendor: 'Upstash',
    category: 'infrastructure',
    icon: '⬆️',
    description: 'Serverless data platform for Redis, Kafka, and QStash.',
    features: 'Redis, Kafka, QStash, Global replication, REST API, Edge-compatible',
    url: 'https://upstash.com/',
    login_url: 'https://console.upstash.com/login',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'freemium',
  },
  {
    name: 'Redis Cloud',
    vendor: 'Redis',
    category: 'infrastructure',
    icon: '🔴',
    description: 'Managed Redis service with high availability and real-time performance.',
    features: 'In-memory database, Caching, Pub/Sub, Streams, Search, JSON, Time series',
    url: 'https://redis.com/redis-enterprise-cloud/',
    login_url: 'https://app.redislabs.com/login',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'freemium',
  },
  {
    name: 'Elastic Cloud',
    vendor: 'Elastic',
    category: 'infrastructure',
    icon: '🔍',
    description: 'Managed Elasticsearch service for search, observability, and security.',
    features: 'Search, Observability, Security, Machine learning, Kibana, APM',
    url: 'https://www.elastic.co/cloud/',
    login_url: 'https://cloud.elastic.co/login',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'freemium',
  },

  // ============ Feature Flags & Experimentation ============
  {
    name: 'LaunchDarkly',
    vendor: 'LaunchDarkly',
    category: 'development',
    icon: '🚀',
    description: 'Feature management platform for controlling feature releases.',
    features: 'Feature flags, Targeting, Experimentation, Segments, Workflows, SDK support',
    url: 'https://launchdarkly.com/',
    login_url: 'https://app.launchdarkly.com/',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'pro',
  },
  {
    name: 'Split',
    vendor: 'Split.io',
    category: 'development',
    icon: '🔀',
    description: 'Feature delivery platform with feature flags and experimentation.',
    features: 'Feature flags, Targeting, Experimentation, Attribution, Integrations',
    url: 'https://www.split.io/',
    login_url: 'https://app.split.io/',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Statsig',
    vendor: 'Statsig',
    category: 'development',
    icon: '📈',
    description: 'Feature flags and product experimentation platform with analytics.',
    features: 'Feature gates, Experiments, Dynamic config, Holdouts, Analytics, Warehouse native',
    url: 'https://statsig.com/',
    login_url: 'https://console.statsig.com/',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },

  // ============ More AI Tools ============
  {
    name: 'Midjourney',
    vendor: 'Midjourney',
    category: 'design',
    icon: '🎨',
    description: 'AI image generation tool for creating artwork from text prompts.',
    features: 'Text-to-image, Variations, Upscaling, Styles, Blending, Web interface',
    url: 'https://www.midjourney.com/',
    login_url: 'https://www.midjourney.com/account/',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'starter',
  },
  {
    name: 'Runway',
    vendor: 'Runway',
    category: 'design',
    icon: '🎬',
    description: 'AI creative suite for video editing, generation, and visual effects.',
    features: 'Video generation, Image generation, Video editing, Green screen, Motion tracking',
    url: 'https://runwayml.com/',
    login_url: 'https://app.runwayml.com/',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'ElevenLabs',
    vendor: 'ElevenLabs',
    category: 'development',
    icon: '🔊',
    description: 'AI voice synthesis platform for text-to-speech and voice cloning.',
    features: 'Text-to-speech, Voice cloning, Multiple languages, API, Projects, Dubbing',
    url: 'https://elevenlabs.io/',
    login_url: 'https://elevenlabs.io/sign-in',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Replicate',
    vendor: 'Replicate',
    category: 'development',
    icon: '🔄',
    description: 'Platform for running open-source machine learning models in the cloud.',
    features: 'Model hosting, API access, Fine-tuning, Deployments, Community models',
    url: 'https://replicate.com/',
    login_url: 'https://replicate.com/signin',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'freemium',
  },
  {
    name: 'Pinecone',
    vendor: 'Pinecone',
    category: 'infrastructure',
    icon: '🌲',
    description: 'Vector database for building AI applications with semantic search.',
    features: 'Vector database, Similarity search, Filtering, Namespaces, Collections, Serverless',
    url: 'https://www.pinecone.io/',
    login_url: 'https://app.pinecone.io/',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'freemium',
  },

  // ============ Note-taking & Documentation ============
  {
    name: 'Obsidian',
    vendor: 'Obsidian',
    category: 'productivity',
    icon: '💎',
    description: 'Private, local-first markdown knowledge base with linking and plugins.',
    features: 'Markdown, Backlinks, Graph view, Plugins, Sync, Publish, Canvas',
    url: 'https://obsidian.md/',
    login_url: 'https://obsidian.md/account',
    is_paid: true,
    billing_cycle: 'annually',
    license_type: 'freemium',
  },
  {
    name: 'Roam Research',
    vendor: 'Roam Research',
    category: 'productivity',
    icon: '📖',
    description: 'Note-taking tool for networked thought with bidirectional linking.',
    features: 'Bidirectional links, Graph database, Daily notes, Queries, Templates, API',
    url: 'https://roamresearch.com/',
    login_url: 'https://roamresearch.com/#/signin',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'pro',
  },
  {
    name: 'Coda',
    vendor: 'Coda',
    category: 'productivity',
    icon: '📄',
    description: 'All-in-one doc combining documents, spreadsheets, and applications.',
    features: 'Docs, Tables, Formulas, Automations, Packs, Templates, Team spaces',
    url: 'https://coda.io/',
    login_url: 'https://coda.io/signin',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Airtable',
    vendor: 'Airtable',
    category: 'productivity',
    icon: '📊',
    description: 'Low-code platform for building collaborative apps with spreadsheet simplicity.',
    features: 'Databases, Views, Automations, Interfaces, Extensions, Sync, API',
    url: 'https://airtable.com/',
    login_url: 'https://airtable.com/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Gitbook',
    vendor: 'GitBook',
    category: 'development',
    icon: '📚',
    description: 'Documentation platform for teams with Git sync and publishing.',
    features: 'Documentation, Git sync, Collaboration, Publishing, Search, API docs',
    url: 'https://www.gitbook.com/',
    login_url: 'https://app.gitbook.com/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'ReadMe',
    vendor: 'ReadMe',
    category: 'development',
    icon: '📖',
    description: 'Developer hub platform for API documentation and developer experience.',
    features: 'API docs, Interactive explorer, Changelog, Tutorials, Metrics, Custom branding',
    url: 'https://readme.com/',
    login_url: 'https://dash.readme.com/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'starter',
  },

  // ============ File Storage & Sharing ============
  {
    name: 'Dropbox',
    vendor: 'Dropbox',
    category: 'productivity',
    icon: '📦',
    description: 'Cloud file storage and sharing platform with collaboration features.',
    features: 'File sync, Sharing, Paper, Transfer, Sign, Backup, Team spaces',
    url: 'https://www.dropbox.com/',
    login_url: 'https://www.dropbox.com/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Box',
    vendor: 'Box',
    category: 'productivity',
    icon: '📁',
    description: 'Enterprise content management and file sharing platform.',
    features: 'File storage, Collaboration, Workflows, Security, Compliance, Integrations',
    url: 'https://www.box.com/',
    login_url: 'https://account.box.com/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'business',
  },
  {
    name: 'Google Drive',
    vendor: 'Google',
    category: 'productivity',
    icon: '📂',
    description: 'Cloud storage service integrated with Google Workspace.',
    features: 'File storage, Sharing, Real-time collaboration, Search, Offline access',
    url: 'https://drive.google.com/',
    login_url: 'https://drive.google.com/',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },

  // ============ Automation & Integration ============
  {
    name: 'Zapier',
    vendor: 'Zapier',
    category: 'productivity',
    icon: '⚡',
    description: 'Automation platform connecting apps with automated workflows.',
    features: 'App integrations, Zaps, Multi-step workflows, Filters, Formatter, Tables',
    url: 'https://zapier.com/',
    login_url: 'https://zapier.com/app/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Make',
    vendor: 'Make (Integromat)',
    category: 'productivity',
    icon: '🔧',
    description: 'Visual automation platform for connecting apps and designing workflows.',
    features: 'Visual builder, Scenarios, Data mapping, Error handling, Webhooks, API',
    url: 'https://www.make.com/',
    login_url: 'https://www.make.com/en/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'n8n',
    vendor: 'n8n',
    category: 'productivity',
    icon: '🔗',
    description: 'Open-source workflow automation tool with self-hosting option.',
    features: 'Visual workflows, Code nodes, Self-hosting, Webhooks, Credentials, Templates',
    url: 'https://n8n.io/',
    login_url: 'https://app.n8n.cloud/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Retool',
    vendor: 'Retool',
    category: 'development',
    icon: '🛠️',
    description: 'Low-code platform for building internal tools quickly.',
    features: 'Drag-and-drop, Database connections, APIs, Custom components, Workflows',
    url: 'https://retool.com/',
    login_url: 'https://login.retool.com/',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },

  // ============ Networking & VPN ============
  {
    name: 'Tailscale',
    vendor: 'Tailscale',
    category: 'security',
    icon: '🔒',
    description: 'Zero-config VPN using WireGuard for secure network connectivity.',
    features: 'Mesh VPN, Zero-config, SSO, ACLs, Magic DNS, Exit nodes, Subnet routing',
    url: 'https://tailscale.com/',
    login_url: 'https://login.tailscale.com/',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Ngrok',
    vendor: 'Ngrok',
    category: 'development',
    icon: '🌐',
    description: 'Secure tunnels to localhost for testing webhooks and APIs.',
    features: 'Secure tunnels, Custom domains, Traffic inspection, OAuth, IP restrictions',
    url: 'https://ngrok.com/',
    login_url: 'https://dashboard.ngrok.com/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
];

// Group templates by category for easier browsing
export const templatesByCategory = serviceTemplates.reduce((acc, template) => {
  if (!acc[template.category]) {
    acc[template.category] = [];
  }
  acc[template.category].push(template);
  return acc;
}, {} as Record<string, ServiceTemplate[]>);

// Search templates
export const searchTemplates = (query: string): ServiceTemplate[] => {
  const lowerQuery = query.toLowerCase();
  return serviceTemplates.filter(t =>
    t.name.toLowerCase().includes(lowerQuery) ||
    t.vendor.toLowerCase().includes(lowerQuery) ||
    t.description.toLowerCase().includes(lowerQuery)
  );
};
