// States/provinces by country code
export interface State {
  code: string;
  name: string;
}

export type StatesByCountry = Record<string, State[]>;

export const statesByCountry: StatesByCountry = {
  US: [
    { code: 'AL', name: 'Alabama' },
    { code: 'AK', name: 'Alaska' },
    { code: 'AZ', name: 'Arizona' },
    { code: 'AR', name: 'Arkansas' },
    { code: 'CA', name: 'California' },
    { code: 'CO', name: 'Colorado' },
    { code: 'CT', name: 'Connecticut' },
    { code: 'DE', name: 'Delaware' },
    { code: 'DC', name: 'District of Columbia' },
    { code: 'FL', name: 'Florida' },
    { code: 'GA', name: 'Georgia' },
    { code: 'HI', name: 'Hawaii' },
    { code: 'ID', name: 'Idaho' },
    { code: 'IL', name: 'Illinois' },
    { code: 'IN', name: 'Indiana' },
    { code: 'IA', name: 'Iowa' },
    { code: 'KS', name: 'Kansas' },
    { code: 'KY', name: 'Kentucky' },
    { code: 'LA', name: 'Louisiana' },
    { code: 'ME', name: 'Maine' },
    { code: 'MD', name: 'Maryland' },
    { code: 'MA', name: 'Massachusetts' },
    { code: 'MI', name: 'Michigan' },
    { code: 'MN', name: 'Minnesota' },
    { code: 'MS', name: 'Mississippi' },
    { code: 'MO', name: 'Missouri' },
    { code: 'MT', name: 'Montana' },
    { code: 'NE', name: 'Nebraska' },
    { code: 'NV', name: 'Nevada' },
    { code: 'NH', name: 'New Hampshire' },
    { code: 'NJ', name: 'New Jersey' },
    { code: 'NM', name: 'New Mexico' },
    { code: 'NY', name: 'New York' },
    { code: 'NC', name: 'North Carolina' },
    { code: 'ND', name: 'North Dakota' },
    { code: 'OH', name: 'Ohio' },
    { code: 'OK', name: 'Oklahoma' },
    { code: 'OR', name: 'Oregon' },
    { code: 'PA', name: 'Pennsylvania' },
    { code: 'RI', name: 'Rhode Island' },
    { code: 'SC', name: 'South Carolina' },
    { code: 'SD', name: 'South Dakota' },
    { code: 'TN', name: 'Tennessee' },
    { code: 'TX', name: 'Texas' },
    { code: 'UT', name: 'Utah' },
    { code: 'VT', name: 'Vermont' },
    { code: 'VA', name: 'Virginia' },
    { code: 'WA', name: 'Washington' },
    { code: 'WV', name: 'West Virginia' },
    { code: 'WI', name: 'Wisconsin' },
    { code: 'WY', name: 'Wyoming' },
  ],
  CA: [
    { code: 'AB', name: 'Alberta' },
    { code: 'BC', name: 'British Columbia' },
    { code: 'MB', name: 'Manitoba' },
    { code: 'NB', name: 'New Brunswick' },
    { code: 'NL', name: 'Newfoundland and Labrador' },
    { code: 'NS', name: 'Nova Scotia' },
    { code: 'NT', name: 'Northwest Territories' },
    { code: 'NU', name: 'Nunavut' },
    { code: 'ON', name: 'Ontario' },
    { code: 'PE', name: 'Prince Edward Island' },
    { code: 'QC', name: 'Quebec' },
    { code: 'SK', name: 'Saskatchewan' },
    { code: 'YT', name: 'Yukon' },
  ],
  AU: [
    { code: 'ACT', name: 'Australian Capital Territory' },
    { code: 'NSW', name: 'New South Wales' },
    { code: 'NT', name: 'Northern Territory' },
    { code: 'QLD', name: 'Queensland' },
    { code: 'SA', name: 'South Australia' },
    { code: 'TAS', name: 'Tasmania' },
    { code: 'VIC', name: 'Victoria' },
    { code: 'WA', name: 'Western Australia' },
  ],
  GB: [
    { code: 'ENG', name: 'England' },
    { code: 'NIR', name: 'Northern Ireland' },
    { code: 'SCT', name: 'Scotland' },
    { code: 'WLS', name: 'Wales' },
  ],
  DE: [
    { code: 'BW', name: 'Baden-Württemberg' },
    { code: 'BY', name: 'Bavaria' },
    { code: 'BE', name: 'Berlin' },
    { code: 'BB', name: 'Brandenburg' },
    { code: 'HB', name: 'Bremen' },
    { code: 'HH', name: 'Hamburg' },
    { code: 'HE', name: 'Hesse' },
    { code: 'MV', name: 'Mecklenburg-Vorpommern' },
    { code: 'NI', name: 'Lower Saxony' },
    { code: 'NW', name: 'North Rhine-Westphalia' },
    { code: 'RP', name: 'Rhineland-Palatinate' },
    { code: 'SL', name: 'Saarland' },
    { code: 'SN', name: 'Saxony' },
    { code: 'ST', name: 'Saxony-Anhalt' },
    { code: 'SH', name: 'Schleswig-Holstein' },
    { code: 'TH', name: 'Thuringia' },
  ],
  FR: [
    { code: 'ARA', name: 'Auvergne-Rhône-Alpes' },
    { code: 'BFC', name: 'Bourgogne-Franche-Comté' },
    { code: 'BRE', name: 'Brittany' },
    { code: 'CVL', name: 'Centre-Val de Loire' },
    { code: 'COR', name: 'Corsica' },
    { code: 'GES', name: 'Grand Est' },
    { code: 'HDF', name: 'Hauts-de-France' },
    { code: 'IDF', name: 'Île-de-France' },
    { code: 'NOR', name: 'Normandy' },
    { code: 'NAQ', name: 'Nouvelle-Aquitaine' },
    { code: 'OCC', name: 'Occitanie' },
    { code: 'PDL', name: 'Pays de la Loire' },
    { code: 'PAC', name: 'Provence-Alpes-Côte d\'Azur' },
  ],
  MX: [
    { code: 'AGU', name: 'Aguascalientes' },
    { code: 'BCN', name: 'Baja California' },
    { code: 'BCS', name: 'Baja California Sur' },
    { code: 'CAM', name: 'Campeche' },
    { code: 'CHP', name: 'Chiapas' },
    { code: 'CHH', name: 'Chihuahua' },
    { code: 'CMX', name: 'Mexico City' },
    { code: 'COA', name: 'Coahuila' },
    { code: 'COL', name: 'Colima' },
    { code: 'DUR', name: 'Durango' },
    { code: 'GUA', name: 'Guanajuato' },
    { code: 'GRO', name: 'Guerrero' },
    { code: 'HID', name: 'Hidalgo' },
    { code: 'JAL', name: 'Jalisco' },
    { code: 'MEX', name: 'México' },
    { code: 'MIC', name: 'Michoacán' },
    { code: 'MOR', name: 'Morelos' },
    { code: 'NAY', name: 'Nayarit' },
    { code: 'NLE', name: 'Nuevo León' },
    { code: 'OAX', name: 'Oaxaca' },
    { code: 'PUE', name: 'Puebla' },
    { code: 'QUE', name: 'Querétaro' },
    { code: 'ROO', name: 'Quintana Roo' },
    { code: 'SLP', name: 'San Luis Potosí' },
    { code: 'SIN', name: 'Sinaloa' },
    { code: 'SON', name: 'Sonora' },
    { code: 'TAB', name: 'Tabasco' },
    { code: 'TAM', name: 'Tamaulipas' },
    { code: 'TLA', name: 'Tlaxcala' },
    { code: 'VER', name: 'Veracruz' },
    { code: 'YUC', name: 'Yucatán' },
    { code: 'ZAC', name: 'Zacatecas' },
  ],
  BR: [
    { code: 'AC', name: 'Acre' },
    { code: 'AL', name: 'Alagoas' },
    { code: 'AP', name: 'Amapá' },
    { code: 'AM', name: 'Amazonas' },
    { code: 'BA', name: 'Bahia' },
    { code: 'CE', name: 'Ceará' },
    { code: 'DF', name: 'Distrito Federal' },
    { code: 'ES', name: 'Espírito Santo' },
    { code: 'GO', name: 'Goiás' },
    { code: 'MA', name: 'Maranhão' },
    { code: 'MT', name: 'Mato Grosso' },
    { code: 'MS', name: 'Mato Grosso do Sul' },
    { code: 'MG', name: 'Minas Gerais' },
    { code: 'PA', name: 'Pará' },
    { code: 'PB', name: 'Paraíba' },
    { code: 'PR', name: 'Paraná' },
    { code: 'PE', name: 'Pernambuco' },
    { code: 'PI', name: 'Piauí' },
    { code: 'RJ', name: 'Rio de Janeiro' },
    { code: 'RN', name: 'Rio Grande do Norte' },
    { code: 'RS', name: 'Rio Grande do Sul' },
    { code: 'RO', name: 'Rondônia' },
    { code: 'RR', name: 'Roraima' },
    { code: 'SC', name: 'Santa Catarina' },
    { code: 'SP', name: 'São Paulo' },
    { code: 'SE', name: 'Sergipe' },
    { code: 'TO', name: 'Tocantins' },
  ],
  IN: [
    { code: 'AN', name: 'Andaman and Nicobar Islands' },
    { code: 'AP', name: 'Andhra Pradesh' },
    { code: 'AR', name: 'Arunachal Pradesh' },
    { code: 'AS', name: 'Assam' },
    { code: 'BR', name: 'Bihar' },
    { code: 'CH', name: 'Chandigarh' },
    { code: 'CT', name: 'Chhattisgarh' },
    { code: 'DN', name: 'Dadra and Nagar Haveli and Daman and Diu' },
    { code: 'DL', name: 'Delhi' },
    { code: 'GA', name: 'Goa' },
    { code: 'GJ', name: 'Gujarat' },
    { code: 'HR', name: 'Haryana' },
    { code: 'HP', name: 'Himachal Pradesh' },
    { code: 'JK', name: 'Jammu and Kashmir' },
    { code: 'JH', name: 'Jharkhand' },
    { code: 'KA', name: 'Karnataka' },
    { code: 'KL', name: 'Kerala' },
    { code: 'LA', name: 'Ladakh' },
    { code: 'LD', name: 'Lakshadweep' },
    { code: 'MP', name: 'Madhya Pradesh' },
    { code: 'MH', name: 'Maharashtra' },
    { code: 'MN', name: 'Manipur' },
    { code: 'ML', name: 'Meghalaya' },
    { code: 'MZ', name: 'Mizoram' },
    { code: 'NL', name: 'Nagaland' },
    { code: 'OR', name: 'Odisha' },
    { code: 'PY', name: 'Puducherry' },
    { code: 'PB', name: 'Punjab' },
    { code: 'RJ', name: 'Rajasthan' },
    { code: 'SK', name: 'Sikkim' },
    { code: 'TN', name: 'Tamil Nadu' },
    { code: 'TG', name: 'Telangana' },
    { code: 'TR', name: 'Tripura' },
    { code: 'UP', name: 'Uttar Pradesh' },
    { code: 'UT', name: 'Uttarakhand' },
    { code: 'WB', name: 'West Bengal' },
  ],
  JP: [
    { code: 'JP-01', name: 'Hokkaido' },
    { code: 'JP-02', name: 'Aomori' },
    { code: 'JP-03', name: 'Iwate' },
    { code: 'JP-04', name: 'Miyagi' },
    { code: 'JP-05', name: 'Akita' },
    { code: 'JP-06', name: 'Yamagata' },
    { code: 'JP-07', name: 'Fukushima' },
    { code: 'JP-08', name: 'Ibaraki' },
    { code: 'JP-09', name: 'Tochigi' },
    { code: 'JP-10', name: 'Gunma' },
    { code: 'JP-11', name: 'Saitama' },
    { code: 'JP-12', name: 'Chiba' },
    { code: 'JP-13', name: 'Tokyo' },
    { code: 'JP-14', name: 'Kanagawa' },
    { code: 'JP-15', name: 'Niigata' },
    { code: 'JP-16', name: 'Toyama' },
    { code: 'JP-17', name: 'Ishikawa' },
    { code: 'JP-18', name: 'Fukui' },
    { code: 'JP-19', name: 'Yamanashi' },
    { code: 'JP-20', name: 'Nagano' },
    { code: 'JP-21', name: 'Gifu' },
    { code: 'JP-22', name: 'Shizuoka' },
    { code: 'JP-23', name: 'Aichi' },
    { code: 'JP-24', name: 'Mie' },
    { code: 'JP-25', name: 'Shiga' },
    { code: 'JP-26', name: 'Kyoto' },
    { code: 'JP-27', name: 'Osaka' },
    { code: 'JP-28', name: 'Hyogo' },
    { code: 'JP-29', name: 'Nara' },
    { code: 'JP-30', name: 'Wakayama' },
    { code: 'JP-31', name: 'Tottori' },
    { code: 'JP-32', name: 'Shimane' },
    { code: 'JP-33', name: 'Okayama' },
    { code: 'JP-34', name: 'Hiroshima' },
    { code: 'JP-35', name: 'Yamaguchi' },
    { code: 'JP-36', name: 'Tokushima' },
    { code: 'JP-37', name: 'Kagawa' },
    { code: 'JP-38', name: 'Ehime' },
    { code: 'JP-39', name: 'Kochi' },
    { code: 'JP-40', name: 'Fukuoka' },
    { code: 'JP-41', name: 'Saga' },
    { code: 'JP-42', name: 'Nagasaki' },
    { code: 'JP-43', name: 'Kumamoto' },
    { code: 'JP-44', name: 'Oita' },
    { code: 'JP-45', name: 'Miyazaki' },
    { code: 'JP-46', name: 'Kagoshima' },
    { code: 'JP-47', name: 'Okinawa' },
  ],
  CN: [
    { code: 'AH', name: 'Anhui' },
    { code: 'BJ', name: 'Beijing' },
    { code: 'CQ', name: 'Chongqing' },
    { code: 'FJ', name: 'Fujian' },
    { code: 'GS', name: 'Gansu' },
    { code: 'GD', name: 'Guangdong' },
    { code: 'GX', name: 'Guangxi' },
    { code: 'GZ', name: 'Guizhou' },
    { code: 'HI', name: 'Hainan' },
    { code: 'HE', name: 'Hebei' },
    { code: 'HL', name: 'Heilongjiang' },
    { code: 'HA', name: 'Henan' },
    { code: 'HB', name: 'Hubei' },
    { code: 'HN', name: 'Hunan' },
    { code: 'JS', name: 'Jiangsu' },
    { code: 'JX', name: 'Jiangxi' },
    { code: 'JL', name: 'Jilin' },
    { code: 'LN', name: 'Liaoning' },
    { code: 'NM', name: 'Inner Mongolia' },
    { code: 'NX', name: 'Ningxia' },
    { code: 'QH', name: 'Qinghai' },
    { code: 'SN', name: 'Shaanxi' },
    { code: 'SD', name: 'Shandong' },
    { code: 'SH', name: 'Shanghai' },
    { code: 'SX', name: 'Shanxi' },
    { code: 'SC', name: 'Sichuan' },
    { code: 'TJ', name: 'Tianjin' },
    { code: 'XJ', name: 'Xinjiang' },
    { code: 'XZ', name: 'Tibet' },
    { code: 'YN', name: 'Yunnan' },
    { code: 'ZJ', name: 'Zhejiang' },
  ],
  IT: [
    { code: 'ABR', name: 'Abruzzo' },
    { code: 'BAS', name: 'Basilicata' },
    { code: 'CAL', name: 'Calabria' },
    { code: 'CAM', name: 'Campania' },
    { code: 'EMR', name: 'Emilia-Romagna' },
    { code: 'FVG', name: 'Friuli-Venezia Giulia' },
    { code: 'LAZ', name: 'Lazio' },
    { code: 'LIG', name: 'Liguria' },
    { code: 'LOM', name: 'Lombardy' },
    { code: 'MAR', name: 'Marche' },
    { code: 'MOL', name: 'Molise' },
    { code: 'PMN', name: 'Piedmont' },
    { code: 'PUG', name: 'Apulia' },
    { code: 'SAR', name: 'Sardinia' },
    { code: 'SIC', name: 'Sicily' },
    { code: 'TOS', name: 'Tuscany' },
    { code: 'TAA', name: 'Trentino-Alto Adige' },
    { code: 'UMB', name: 'Umbria' },
    { code: 'VDA', name: 'Aosta Valley' },
    { code: 'VEN', name: 'Veneto' },
  ],
  ES: [
    { code: 'AN', name: 'Andalusia' },
    { code: 'AR', name: 'Aragon' },
    { code: 'AS', name: 'Asturias' },
    { code: 'IB', name: 'Balearic Islands' },
    { code: 'PV', name: 'Basque Country' },
    { code: 'CN', name: 'Canary Islands' },
    { code: 'CB', name: 'Cantabria' },
    { code: 'CL', name: 'Castile and León' },
    { code: 'CM', name: 'Castilla-La Mancha' },
    { code: 'CT', name: 'Catalonia' },
    { code: 'CE', name: 'Ceuta' },
    { code: 'EX', name: 'Extremadura' },
    { code: 'GA', name: 'Galicia' },
    { code: 'RI', name: 'La Rioja' },
    { code: 'MD', name: 'Madrid' },
    { code: 'ML', name: 'Melilla' },
    { code: 'MC', name: 'Murcia' },
    { code: 'NC', name: 'Navarre' },
    { code: 'VC', name: 'Valencia' },
  ],
  NL: [
    { code: 'DR', name: 'Drenthe' },
    { code: 'FL', name: 'Flevoland' },
    { code: 'FR', name: 'Friesland' },
    { code: 'GE', name: 'Gelderland' },
    { code: 'GR', name: 'Groningen' },
    { code: 'LI', name: 'Limburg' },
    { code: 'NB', name: 'North Brabant' },
    { code: 'NH', name: 'North Holland' },
    { code: 'OV', name: 'Overijssel' },
    { code: 'ZH', name: 'South Holland' },
    { code: 'UT', name: 'Utrecht' },
    { code: 'ZE', name: 'Zeeland' },
  ],
};

// Get states for a country
export function getStatesForCountry(countryCode: string): State[] {
  return statesByCountry[countryCode] || [];
}

// Check if a country has states/provinces
export function countryHasStates(countryCode: string): boolean {
  return countryCode in statesByCountry && statesByCountry[countryCode].length > 0;
}

// Get state by code within a country
export function getStateByCode(countryCode: string, stateCode: string): State | undefined {
  const states = statesByCountry[countryCode];
  if (!states) return undefined;
  return states.find(s => s.code === stateCode);
}

// Get state by name within a country
export function getStateByName(countryCode: string, stateName: string): State | undefined {
  const states = statesByCountry[countryCode];
  if (!states) return undefined;
  return states.find(s => s.name.toLowerCase() === stateName.toLowerCase());
}
